// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this CommunityIAMBinding.
func (mg *CommunityIAMBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CommunityID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CommunityIDRef,
		Selector:     mg.Spec.ForProvider.CommunityIDSelector,
		To: reference.To{
			List:    &CommunityList{},
			Managed: &Community{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CommunityID")
	}
	mg.Spec.ForProvider.CommunityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CommunityIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CommunityID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CommunityIDRef,
		Selector:     mg.Spec.InitProvider.CommunityIDSelector,
		To: reference.To{
			List:    &CommunityList{},
			Managed: &Community{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CommunityID")
	}
	mg.Spec.InitProvider.CommunityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CommunityIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Project.
func (mg *Project) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CommunityID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CommunityIDRef,
		Selector:     mg.Spec.ForProvider.CommunityIDSelector,
		To: reference.To{
			List:    &CommunityList{},
			Managed: &Community{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CommunityID")
	}
	mg.Spec.ForProvider.CommunityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CommunityIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CommunityID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CommunityIDRef,
		Selector:     mg.Spec.InitProvider.CommunityIDSelector,
		To: reference.To{
			List:    &CommunityList{},
			Managed: &Community{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CommunityID")
	}
	mg.Spec.InitProvider.CommunityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CommunityIDRef = rsp.ResolvedReference

	return nil
}
