apiVersion: container.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: RegistryIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/registryiambinding
  labels:
    testing.upbound.io/example-name: puller
  name: puller
spec:
  forProvider:
    registryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: your-registry
    role: container-registry.images.puller
    serviceAccountRef:
    - name: example

---

apiVersion: container.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/registryiambinding
  labels:
    testing.upbound.io/example-name: your-registry
  name: your-registry
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: registry-name
