apiVersion: container.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: my-repository
  name: my-repository
spec:
  forProvider:
    name: ${yandex_container_registry.my-registry.id}/test-repository

---

apiVersion: container.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: my-registry
  name: my-registry
spec:
  forProvider:
    name: test-registry
