apiVersion: dataproc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    clusterConfig:
    - hadoop:
      - initializationAction:
        - args:
          - arg1
          - arg2
          uri: s3a://yandex_storage_bucket.foo.bucket/scripts/script.sh
        properties:
          yarn:yarn.resourcemanager.am.max-attempts: 5
        services:
        - HDFS
        - YARN
        - SPARK
        - TEZ
        - MAPREDUCE
        - HIVE
        sshPublicKeys:
        - ${file("~/.ssh/id_rsa.pub")}
      subclusterSpec:
      - hostsCount: 1
        name: main
        resources:
        - diskSize: 20
          diskTypeId: network-hdd
          resourcePresetId: s2.small
        role: MASTERNODE
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: foo
      - hostsCount: 2
        name: data
        resources:
        - diskSize: 20
          diskTypeId: network-hdd
          resourcePresetId: s2.small
        role: DATANODE
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: foo
      - hostsCount: 2
        name: compute
        resources:
        - diskSize: 20
          diskTypeId: network-hdd
          resourcePresetId: s2.small
        role: COMPUTENODE
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: foo
      - autoscalingConfig:
        - decommissionTimeout: 60
          maxHostsCount: 10
          measurementDuration: 60
          preemptible: false
          stabilizationDuration: 120
          warmupDuration: 60
        hostsCount: 2
        name: compute_autoscaling
        resources:
        - diskSize: 20
          diskTypeId: network-hdd
          resourcePresetId: s2.small
        role: COMPUTENODE
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: foo
    description: Dataproc Cluster created by Terraform
    labels:
      created_by: terraform
    name: dataproc-cluster
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: dataproc
    zoneId: ru-central1-b

---

apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: dataproc
  name: dataproc
spec:
  forProvider:
    description: service account to manage Dataproc Cluster
    name: dataproc

---

apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccountStaticAccessKey
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: dataproc

---

apiVersion: resourcemanager.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: bucket-creator
  name: bucket-creator
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager_folder
    members:
    - serviceAccount:${yandex_iam_service_account.dataproc.id}
    role: editor

---

apiVersion: resourcemanager.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: dataproc
  name: dataproc
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager_folder
    members:
    - serviceAccount:${yandex_iam_service_account.dataproc.id}
    role: mdb.dataproc.agent

---

apiVersion: storage.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    accessKeySelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    bucket: foo
    secretKeySecretRef:
      key: attribute.secret_key
      name: example-iam-service-account-static-access-key
      namespace: upbound-system

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.1.0.0/24
    zone: ru-central1-b
