apiVersion: cdn.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: OriginGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1alpha1/origingroup
  labels:
    testing.upbound.io/example-name: my_group
  name: my-group
spec:
  forProvider:
    name: My Origin group
    origin:
    - source: ya.ru
    - source: yandex.ru
    - source: goo.gl
    - backup: false
      source: amazon.com
    useNext: true
