apiVersion: cdn.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1alpha1/resource
  labels:
    testing.upbound.io/example-name: my_resource
  name: my-resource
spec:
  forProvider:
    active: false
    cname: cdn1.yandex-example.ru
    options:
    - edgeCacheSettings: 345600
      ignoreCookie: true
      staticRequestHeaders:
        is-from-cdn: "yes"
      staticResponseHeaders:
        is-cdn: "yes"
    originGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo_cdn_group_by_id
    originProtocol: https
    secondaryHostnames:
    - cdn-example-1.yandex.ru
    - cdn-example-2.yandex.ru
