apiVersion: gitlab.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: gitlab/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: my_gitlab_instance
  name: my-gitlab-instance
  namespace: upbound-system
spec:
  forProvider:
    adminEmail: gitlab-user@example.com
    adminLogin: gitlab-user
    backupRetainPeriodDays: 7
    diskSize: 30
    domain: gitlab-terraform.gitlab.yandexcloud.net
    name: gitlab-created-with-terraform
    resourcePresetId: s2.micro
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: a
