apiVersion: lb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: TargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/targetgroup
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: my-target-group
    regionId: ru-central1
    target:
    - address: ${yandex_compute_instance.my-instance-1.network_interface.0.ip_address}
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: my-subnet
    - address: ${yandex_compute_instance.my-instance-2.network_interface.0.ip_address}
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: my-subnet
