//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootDiskInitParameters) DeepCopyInto(out *BootDiskInitParameters) {
	*out = *in
	if in.InitializeParams != nil {
		in, out := &in.InitializeParams, &out.InitializeParams
		*out = new(InitializeParamsInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootDiskInitParameters.
func (in *BootDiskInitParameters) DeepCopy() *BootDiskInitParameters {
	if in == nil {
		return nil
	}
	out := new(BootDiskInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootDiskObservation) DeepCopyInto(out *BootDiskObservation) {
	*out = *in
	if in.InitializeParams != nil {
		in, out := &in.InitializeParams, &out.InitializeParams
		*out = new(InitializeParamsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootDiskObservation.
func (in *BootDiskObservation) DeepCopy() *BootDiskObservation {
	if in == nil {
		return nil
	}
	out := new(BootDiskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootDiskParameters) DeepCopyInto(out *BootDiskParameters) {
	*out = *in
	if in.InitializeParams != nil {
		in, out := &in.InitializeParams, &out.InitializeParams
		*out = new(InitializeParamsParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootDiskParameters.
func (in *BootDiskParameters) DeepCopy() *BootDiskParameters {
	if in == nil {
		return nil
	}
	out := new(BootDiskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDiskInitParameters) DeepCopyInto(out *DataDiskInitParameters) {
	*out = *in
	if in.InitializeParams != nil {
		in, out := &in.InitializeParams, &out.InitializeParams
		*out = new(DataDiskInitializeParamsInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDiskInitParameters.
func (in *DataDiskInitParameters) DeepCopy() *DataDiskInitParameters {
	if in == nil {
		return nil
	}
	out := new(DataDiskInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDiskInitializeParamsInitParameters) DeepCopyInto(out *DataDiskInitializeParamsInitParameters) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDiskInitializeParamsInitParameters.
func (in *DataDiskInitializeParamsInitParameters) DeepCopy() *DataDiskInitializeParamsInitParameters {
	if in == nil {
		return nil
	}
	out := new(DataDiskInitializeParamsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDiskInitializeParamsObservation) DeepCopyInto(out *DataDiskInitializeParamsObservation) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDiskInitializeParamsObservation.
func (in *DataDiskInitializeParamsObservation) DeepCopy() *DataDiskInitializeParamsObservation {
	if in == nil {
		return nil
	}
	out := new(DataDiskInitializeParamsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDiskInitializeParamsParameters) DeepCopyInto(out *DataDiskInitializeParamsParameters) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDiskInitializeParamsParameters.
func (in *DataDiskInitializeParamsParameters) DeepCopy() *DataDiskInitializeParamsParameters {
	if in == nil {
		return nil
	}
	out := new(DataDiskInitializeParamsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDiskObservation) DeepCopyInto(out *DataDiskObservation) {
	*out = *in
	if in.InitializeParams != nil {
		in, out := &in.InitializeParams, &out.InitializeParams
		*out = new(DataDiskInitializeParamsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDiskObservation.
func (in *DataDiskObservation) DeepCopy() *DataDiskObservation {
	if in == nil {
		return nil
	}
	out := new(DataDiskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDiskParameters) DeepCopyInto(out *DataDiskParameters) {
	*out = *in
	if in.InitializeParams != nil {
		in, out := &in.InitializeParams, &out.InitializeParams
		*out = new(DataDiskInitializeParamsParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDiskParameters.
func (in *DataDiskParameters) DeepCopy() *DataDiskParameters {
	if in == nil {
		return nil
	}
	out := new(DataDiskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopTemplateInitParameters) DeepCopyInto(out *DesktopTemplateInitParameters) {
	*out = *in
	if in.BootDisk != nil {
		in, out := &in.BootDisk, &out.BootDisk
		*out = new(BootDiskInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.DataDisk != nil {
		in, out := &in.DataDisk, &out.DataDisk
		*out = new(DataDiskInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInterface != nil {
		in, out := &in.NetworkInterface, &out.NetworkInterface
		*out = new(DesktopTemplateNetworkInterfaceInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourcesInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopTemplateInitParameters.
func (in *DesktopTemplateInitParameters) DeepCopy() *DesktopTemplateInitParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopTemplateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopTemplateNetworkInterfaceInitParameters) DeepCopyInto(out *DesktopTemplateNetworkInterfaceInitParameters) {
	*out = *in
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.SubnetIds != nil {
		in, out := &in.SubnetIds, &out.SubnetIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopTemplateNetworkInterfaceInitParameters.
func (in *DesktopTemplateNetworkInterfaceInitParameters) DeepCopy() *DesktopTemplateNetworkInterfaceInitParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopTemplateNetworkInterfaceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopTemplateNetworkInterfaceObservation) DeepCopyInto(out *DesktopTemplateNetworkInterfaceObservation) {
	*out = *in
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.SubnetIds != nil {
		in, out := &in.SubnetIds, &out.SubnetIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopTemplateNetworkInterfaceObservation.
func (in *DesktopTemplateNetworkInterfaceObservation) DeepCopy() *DesktopTemplateNetworkInterfaceObservation {
	if in == nil {
		return nil
	}
	out := new(DesktopTemplateNetworkInterfaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopTemplateNetworkInterfaceParameters) DeepCopyInto(out *DesktopTemplateNetworkInterfaceParameters) {
	*out = *in
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.SubnetIds != nil {
		in, out := &in.SubnetIds, &out.SubnetIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopTemplateNetworkInterfaceParameters.
func (in *DesktopTemplateNetworkInterfaceParameters) DeepCopy() *DesktopTemplateNetworkInterfaceParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopTemplateNetworkInterfaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopTemplateObservation) DeepCopyInto(out *DesktopTemplateObservation) {
	*out = *in
	if in.BootDisk != nil {
		in, out := &in.BootDisk, &out.BootDisk
		*out = new(BootDiskObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.DataDisk != nil {
		in, out := &in.DataDisk, &out.DataDisk
		*out = new(DataDiskObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInterface != nil {
		in, out := &in.NetworkInterface, &out.NetworkInterface
		*out = new(DesktopTemplateNetworkInterfaceObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourcesObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopTemplateObservation.
func (in *DesktopTemplateObservation) DeepCopy() *DesktopTemplateObservation {
	if in == nil {
		return nil
	}
	out := new(DesktopTemplateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopTemplateParameters) DeepCopyInto(out *DesktopTemplateParameters) {
	*out = *in
	if in.BootDisk != nil {
		in, out := &in.BootDisk, &out.BootDisk
		*out = new(BootDiskParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.DataDisk != nil {
		in, out := &in.DataDisk, &out.DataDisk
		*out = new(DataDiskParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInterface != nil {
		in, out := &in.NetworkInterface, &out.NetworkInterface
		*out = new(DesktopTemplateNetworkInterfaceParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourcesParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopTemplateParameters.
func (in *DesktopTemplateParameters) DeepCopy() *DesktopTemplateParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopTemplateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktop) DeepCopyInto(out *DesktopsDesktop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktop.
func (in *DesktopsDesktop) DeepCopy() *DesktopsDesktop {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopsDesktop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopGroup) DeepCopyInto(out *DesktopsDesktopGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopGroup.
func (in *DesktopsDesktopGroup) DeepCopy() *DesktopsDesktopGroup {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopsDesktopGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopGroupInitParameters) DeepCopyInto(out *DesktopsDesktopGroupInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DesktopTemplate != nil {
		in, out := &in.DesktopTemplate, &out.DesktopTemplate
		*out = new(DesktopTemplateInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.FolderIDRef != nil {
		in, out := &in.FolderIDRef, &out.FolderIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FolderIDSelector != nil {
		in, out := &in.FolderIDSelector, &out.FolderIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupConfig != nil {
		in, out := &in.GroupConfig, &out.GroupConfig
		*out = new(GroupConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopGroupInitParameters.
func (in *DesktopsDesktopGroupInitParameters) DeepCopy() *DesktopsDesktopGroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopGroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopGroupList) DeepCopyInto(out *DesktopsDesktopGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesktopsDesktopGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopGroupList.
func (in *DesktopsDesktopGroupList) DeepCopy() *DesktopsDesktopGroupList {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopsDesktopGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopGroupObservation) DeepCopyInto(out *DesktopsDesktopGroupObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DesktopGroupID != nil {
		in, out := &in.DesktopGroupID, &out.DesktopGroupID
		*out = new(string)
		**out = **in
	}
	if in.DesktopTemplate != nil {
		in, out := &in.DesktopTemplate, &out.DesktopTemplate
		*out = new(DesktopTemplateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.GroupConfig != nil {
		in, out := &in.GroupConfig, &out.GroupConfig
		*out = new(GroupConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopGroupObservation.
func (in *DesktopsDesktopGroupObservation) DeepCopy() *DesktopsDesktopGroupObservation {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopGroupParameters) DeepCopyInto(out *DesktopsDesktopGroupParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DesktopTemplate != nil {
		in, out := &in.DesktopTemplate, &out.DesktopTemplate
		*out = new(DesktopTemplateParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.FolderIDRef != nil {
		in, out := &in.FolderIDRef, &out.FolderIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FolderIDSelector != nil {
		in, out := &in.FolderIDSelector, &out.FolderIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupConfig != nil {
		in, out := &in.GroupConfig, &out.GroupConfig
		*out = new(GroupConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopGroupParameters.
func (in *DesktopsDesktopGroupParameters) DeepCopy() *DesktopsDesktopGroupParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopGroupSpec) DeepCopyInto(out *DesktopsDesktopGroupSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopGroupSpec.
func (in *DesktopsDesktopGroupSpec) DeepCopy() *DesktopsDesktopGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopGroupStatus) DeepCopyInto(out *DesktopsDesktopGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopGroupStatus.
func (in *DesktopsDesktopGroupStatus) DeepCopy() *DesktopsDesktopGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopInitParameters) DeepCopyInto(out *DesktopsDesktopInitParameters) {
	*out = *in
	if in.DesktopGroupID != nil {
		in, out := &in.DesktopGroupID, &out.DesktopGroupID
		*out = new(string)
		**out = **in
	}
	if in.DesktopGroupIDRef != nil {
		in, out := &in.DesktopGroupIDRef, &out.DesktopGroupIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DesktopGroupIDSelector != nil {
		in, out := &in.DesktopGroupIDSelector, &out.DesktopGroupIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MembersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkInterface != nil {
		in, out := &in.NetworkInterface, &out.NetworkInterface
		*out = new(NetworkInterfaceInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopInitParameters.
func (in *DesktopsDesktopInitParameters) DeepCopy() *DesktopsDesktopInitParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopList) DeepCopyInto(out *DesktopsDesktopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesktopsDesktop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopList.
func (in *DesktopsDesktopList) DeepCopy() *DesktopsDesktopList {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopsDesktopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopObservation) DeepCopyInto(out *DesktopsDesktopObservation) {
	*out = *in
	if in.DesktopGroupID != nil {
		in, out := &in.DesktopGroupID, &out.DesktopGroupID
		*out = new(string)
		**out = **in
	}
	if in.DesktopID != nil {
		in, out := &in.DesktopID, &out.DesktopID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MembersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkInterface != nil {
		in, out := &in.NetworkInterface, &out.NetworkInterface
		*out = new(NetworkInterfaceObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopObservation.
func (in *DesktopsDesktopObservation) DeepCopy() *DesktopsDesktopObservation {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopParameters) DeepCopyInto(out *DesktopsDesktopParameters) {
	*out = *in
	if in.DesktopGroupID != nil {
		in, out := &in.DesktopGroupID, &out.DesktopGroupID
		*out = new(string)
		**out = **in
	}
	if in.DesktopGroupIDRef != nil {
		in, out := &in.DesktopGroupIDRef, &out.DesktopGroupIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DesktopGroupIDSelector != nil {
		in, out := &in.DesktopGroupIDSelector, &out.DesktopGroupIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MembersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkInterface != nil {
		in, out := &in.NetworkInterface, &out.NetworkInterface
		*out = new(NetworkInterfaceParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopParameters.
func (in *DesktopsDesktopParameters) DeepCopy() *DesktopsDesktopParameters {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopSpec) DeepCopyInto(out *DesktopsDesktopSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopSpec.
func (in *DesktopsDesktopSpec) DeepCopy() *DesktopsDesktopSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopsDesktopStatus) DeepCopyInto(out *DesktopsDesktopStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopsDesktopStatus.
func (in *DesktopsDesktopStatus) DeepCopy() *DesktopsDesktopStatus {
	if in == nil {
		return nil
	}
	out := new(DesktopsDesktopStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfigInitParameters) DeepCopyInto(out *GroupConfigInitParameters) {
	*out = *in
	if in.DesktopType != nil {
		in, out := &in.DesktopType, &out.DesktopType
		*out = new(string)
		**out = **in
	}
	if in.MaxDesktopsAmount != nil {
		in, out := &in.MaxDesktopsAmount, &out.MaxDesktopsAmount
		*out = new(float64)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]GroupConfigMembersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinReadyDesktops != nil {
		in, out := &in.MinReadyDesktops, &out.MinReadyDesktops
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfigInitParameters.
func (in *GroupConfigInitParameters) DeepCopy() *GroupConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(GroupConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfigMembersInitParameters) DeepCopyInto(out *GroupConfigMembersInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfigMembersInitParameters.
func (in *GroupConfigMembersInitParameters) DeepCopy() *GroupConfigMembersInitParameters {
	if in == nil {
		return nil
	}
	out := new(GroupConfigMembersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfigMembersObservation) DeepCopyInto(out *GroupConfigMembersObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfigMembersObservation.
func (in *GroupConfigMembersObservation) DeepCopy() *GroupConfigMembersObservation {
	if in == nil {
		return nil
	}
	out := new(GroupConfigMembersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfigMembersParameters) DeepCopyInto(out *GroupConfigMembersParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfigMembersParameters.
func (in *GroupConfigMembersParameters) DeepCopy() *GroupConfigMembersParameters {
	if in == nil {
		return nil
	}
	out := new(GroupConfigMembersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfigObservation) DeepCopyInto(out *GroupConfigObservation) {
	*out = *in
	if in.DesktopType != nil {
		in, out := &in.DesktopType, &out.DesktopType
		*out = new(string)
		**out = **in
	}
	if in.MaxDesktopsAmount != nil {
		in, out := &in.MaxDesktopsAmount, &out.MaxDesktopsAmount
		*out = new(float64)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]GroupConfigMembersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinReadyDesktops != nil {
		in, out := &in.MinReadyDesktops, &out.MinReadyDesktops
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfigObservation.
func (in *GroupConfigObservation) DeepCopy() *GroupConfigObservation {
	if in == nil {
		return nil
	}
	out := new(GroupConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfigParameters) DeepCopyInto(out *GroupConfigParameters) {
	*out = *in
	if in.DesktopType != nil {
		in, out := &in.DesktopType, &out.DesktopType
		*out = new(string)
		**out = **in
	}
	if in.MaxDesktopsAmount != nil {
		in, out := &in.MaxDesktopsAmount, &out.MaxDesktopsAmount
		*out = new(float64)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]GroupConfigMembersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinReadyDesktops != nil {
		in, out := &in.MinReadyDesktops, &out.MinReadyDesktops
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfigParameters.
func (in *GroupConfigParameters) DeepCopy() *GroupConfigParameters {
	if in == nil {
		return nil
	}
	out := new(GroupConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializeParamsInitParameters) DeepCopyInto(out *InitializeParamsInitParameters) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializeParamsInitParameters.
func (in *InitializeParamsInitParameters) DeepCopy() *InitializeParamsInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitializeParamsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializeParamsObservation) DeepCopyInto(out *InitializeParamsObservation) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializeParamsObservation.
func (in *InitializeParamsObservation) DeepCopy() *InitializeParamsObservation {
	if in == nil {
		return nil
	}
	out := new(InitializeParamsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializeParamsParameters) DeepCopyInto(out *InitializeParamsParameters) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializeParamsParameters.
func (in *InitializeParamsParameters) DeepCopy() *InitializeParamsParameters {
	if in == nil {
		return nil
	}
	out := new(InitializeParamsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembersInitParameters) DeepCopyInto(out *MembersInitParameters) {
	*out = *in
	if in.SubjectID != nil {
		in, out := &in.SubjectID, &out.SubjectID
		*out = new(string)
		**out = **in
	}
	if in.SubjectType != nil {
		in, out := &in.SubjectType, &out.SubjectType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembersInitParameters.
func (in *MembersInitParameters) DeepCopy() *MembersInitParameters {
	if in == nil {
		return nil
	}
	out := new(MembersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembersObservation) DeepCopyInto(out *MembersObservation) {
	*out = *in
	if in.SubjectID != nil {
		in, out := &in.SubjectID, &out.SubjectID
		*out = new(string)
		**out = **in
	}
	if in.SubjectType != nil {
		in, out := &in.SubjectType, &out.SubjectType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembersObservation.
func (in *MembersObservation) DeepCopy() *MembersObservation {
	if in == nil {
		return nil
	}
	out := new(MembersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembersParameters) DeepCopyInto(out *MembersParameters) {
	*out = *in
	if in.SubjectID != nil {
		in, out := &in.SubjectID, &out.SubjectID
		*out = new(string)
		**out = **in
	}
	if in.SubjectType != nil {
		in, out := &in.SubjectType, &out.SubjectType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembersParameters.
func (in *MembersParameters) DeepCopy() *MembersParameters {
	if in == nil {
		return nil
	}
	out := new(MembersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceInitParameters) DeepCopyInto(out *NetworkInterfaceInitParameters) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceInitParameters.
func (in *NetworkInterfaceInitParameters) DeepCopy() *NetworkInterfaceInitParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceObservation) DeepCopyInto(out *NetworkInterfaceObservation) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceObservation.
func (in *NetworkInterfaceObservation) DeepCopy() *NetworkInterfaceObservation {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceParameters) DeepCopyInto(out *NetworkInterfaceParameters) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceParameters.
func (in *NetworkInterfaceParameters) DeepCopy() *NetworkInterfaceParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesInitParameters) DeepCopyInto(out *ResourcesInitParameters) {
	*out = *in
	if in.CoreFraction != nil {
		in, out := &in.CoreFraction, &out.CoreFraction
		*out = new(float64)
		**out = **in
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(float64)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesInitParameters.
func (in *ResourcesInitParameters) DeepCopy() *ResourcesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ResourcesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesObservation) DeepCopyInto(out *ResourcesObservation) {
	*out = *in
	if in.CoreFraction != nil {
		in, out := &in.CoreFraction, &out.CoreFraction
		*out = new(float64)
		**out = **in
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(float64)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesObservation.
func (in *ResourcesObservation) DeepCopy() *ResourcesObservation {
	if in == nil {
		return nil
	}
	out := new(ResourcesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesParameters) DeepCopyInto(out *ResourcesParameters) {
	*out = *in
	if in.CoreFraction != nil {
		in, out := &in.CoreFraction, &out.CoreFraction
		*out = new(float64)
		**out = **in
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(float64)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesParameters.
func (in *ResourcesParameters) DeepCopy() *ResourcesParameters {
	if in == nil {
		return nil
	}
	out := new(ResourcesParameters)
	in.DeepCopyInto(out)
	return out
}
