// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *DesktopsDesktop) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DesktopsDesktopGroup) Hub() {}
