apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccountIAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccountiampolicy
  labels:
    testing.upbound.io/example-name: admin-account-iam
  name: admin-account-iam
spec:
  forProvider:
    policyData: ${data.yandex_iam_policy.admin.policy_data}
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
