apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccountAPIKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccountapikey
  labels:
    testing.upbound.io/example-name: sa-api-key
  name: sa-api-key
spec:
  forProvider:
    description: api key for authorization
    pgpKey: keybase:keybaseusername
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
