apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: sa
  name: sa
spec:
  forProvider:
    description: service account to manage VMs
