apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccountIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccountiambinding
  labels:
    testing.upbound.io/example-name: admin-account-iam
  name: admin-account-iam
spec:
  forProvider:
    role: admin
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceAccountRef:
    - name: example
