// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *IAMBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ScalingPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Trigger) Hub() {}
