apiVersion: organizationmanager.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: organizationmanager/v1alpha1/group
  labels:
    testing.upbound.io/example-name: my_group
  name: my-group
  namespace: upbound-system
spec:
  forProvider:
    description: My new Group
    name: my-group
    organizationId: sdf4*********3fr
