apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: DiskPlacementGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/diskplacementgroup
  labels:
    testing.upbound.io/example-name: group1
  name: group1
spec:
  forProvider:
    description: my description
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: test-pg
