apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: FilesystemIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/filesystemiambinding
  labels:
    testing.upbound.io/example-name: editor
  name: editor
spec:
  forProvider:
    filesystemId: ${data.yandex_compute_filesystem.fs1.id}
    members:
    - userAccount:some_user_id
    role: editor

---

apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Filesystem
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/filesystemiambinding
  labels:
    testing.upbound.io/example-name: fs1
  name: fs1
spec:
  forProvider:
    labels:
      environment: test
    name: fs-name
    size: 10
    type: network-ssd
    zone: ru-central1-a
