apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ImageIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/imageiambinding
  labels:
    testing.upbound.io/example-name: editor
  name: editor
spec:
  forProvider:
    imageId: ${data.yandex_compute_image.image1.id}
    members:
    - userAccount:some_user_id
    role: editor

---

apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/imageiambinding
  labels:
    testing.upbound.io/example-name: image1
  name: image1
spec:
  forProvider:
    name: my-custom-image
    sourceUrl: https://storage.yandexcloud.net/lucky-images/kube-it.img
