apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: InstanceIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instanceiambinding
  labels:
    testing.upbound.io/example-name: editor
  name: editor
spec:
  forProvider:
    instanceId: ${data.yandex_compute_instance.instance1.id}
    members:
    - userAccount:some_user_id
    role: editor

---

apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instanceiambinding
  labels:
    testing.upbound.io/example-name: instance1
  name: instance1
spec:
  forProvider:
    bootDisk:
    - diskIdSelector:
        matchLabels:
          testing.upbound.io/example-name: boot-disk
    metadata:
      foo: bar
      ssh-keys: ubuntu:${file("~/.ssh/id_rsa.pub")}
    name: test
    networkInterface:
    - index: 1
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
    platformId: standard-v1
    resources:
    - cores: 2
      memory: 4
    zone: ru-central1-a

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instanceiambinding
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instanceiambinding
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.5.0.0/24
    zone: ru-central1-a
