apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: PlacementGroupIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/placementgroupiambinding
  labels:
    testing.upbound.io/example-name: editor
  name: editor
spec:
  forProvider:
    members:
    - userAccount:some_user_id
    placementGroupId: ${data.yandex_compute_placement_group.pg1.id}
    role: editor

---

apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: PlacementGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/placementgroupiambinding
  labels:
    testing.upbound.io/example-name: pg1
  name: pg1
spec:
  forProvider:
    description: my description
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: test-pg
