apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    labels:
      my-label: my-label-value
    name: test-snapshot
    sourceDiskIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
