apiVersion: backup.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: basic_policy
  name: basic-policy
  namespace: upbound-system
spec:
  forProvider:
    name: basic policy
    reattempts:
    - {}
    retention:
    - afterBackup: false
    scheduling:
    - enabled: false
      executeByInterval: 86400
    vmSnapshotReattempts:
    - {}
