// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClusterIAMMemberInitParameters struct {

	// (String) The ID of the compute cluster to attach the policy to.
	// The ID of the compute `cluster` to attach the policy to.
	// +crossplane:generate:reference:type=github.com/tagesjump/provider-upjet-yc/apis/cluster/kubernetes/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) An array of identities that will be granted the privilege in the role. Each entry can have one of the following values:
	// An array of identities that will be granted the privilege in the `role`. Each entry can have one of the following values:
	// * **userAccount:{user_id}**: A unique user ID that represents a specific Yandex account.
	// * **serviceAccount:{service_account_id}**: A unique service account ID.
	// * **federatedUser:{federated_user_id}**: A unique federated user ID.
	// * **federatedUser:{federated_user_id}:**: A unique SAML federation user account ID.
	// * **group:{group_id}**: A unique group ID.
	// * **system:group:federation:{federation_id}:users**: All users in federation.
	// * **system:group:organization:{organization_id}:users**: All users in organization.
	// * **system:allAuthenticatedUsers**: All authenticated users.
	// * **system:allUsers**: All users, including unauthenticated ones.
	//
	// ~> for more information about system groups, see [Cloud Documentation](https://yandex.cloud/docs/iam/concepts/access-control/system-group).
	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// (String) The role that should be assigned. Only one yandex_kubernetes_cluster_iam_member can be used per role.
	// The role that should be assigned. Only one yandex_kubernetes_cluster_iam_member can be used per role.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (Number) For test purposes, to compensate IAM operations delay
	// For test purposes, to compensate IAM operations delay
	SleepAfter *float64 `json:"sleepAfter,omitempty" tf:"sleep_after,omitempty"`
}

type ClusterIAMMemberObservation struct {

	// (String) The ID of the compute cluster to attach the policy to.
	// The ID of the compute `cluster` to attach the policy to.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) An array of identities that will be granted the privilege in the role. Each entry can have one of the following values:
	// An array of identities that will be granted the privilege in the `role`. Each entry can have one of the following values:
	// * **userAccount:{user_id}**: A unique user ID that represents a specific Yandex account.
	// * **serviceAccount:{service_account_id}**: A unique service account ID.
	// * **federatedUser:{federated_user_id}**: A unique federated user ID.
	// * **federatedUser:{federated_user_id}:**: A unique SAML federation user account ID.
	// * **group:{group_id}**: A unique group ID.
	// * **system:group:federation:{federation_id}:users**: All users in federation.
	// * **system:group:organization:{organization_id}:users**: All users in organization.
	// * **system:allAuthenticatedUsers**: All authenticated users.
	// * **system:allUsers**: All users, including unauthenticated ones.
	//
	// ~> for more information about system groups, see [Cloud Documentation](https://yandex.cloud/docs/iam/concepts/access-control/system-group).
	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// (String) The role that should be assigned. Only one yandex_kubernetes_cluster_iam_member can be used per role.
	// The role that should be assigned. Only one yandex_kubernetes_cluster_iam_member can be used per role.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (Number) For test purposes, to compensate IAM operations delay
	// For test purposes, to compensate IAM operations delay
	SleepAfter *float64 `json:"sleepAfter,omitempty" tf:"sleep_after,omitempty"`
}

type ClusterIAMMemberParameters struct {

	// (String) The ID of the compute cluster to attach the policy to.
	// The ID of the compute `cluster` to attach the policy to.
	// +crossplane:generate:reference:type=github.com/tagesjump/provider-upjet-yc/apis/cluster/kubernetes/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) An array of identities that will be granted the privilege in the role. Each entry can have one of the following values:
	// An array of identities that will be granted the privilege in the `role`. Each entry can have one of the following values:
	// * **userAccount:{user_id}**: A unique user ID that represents a specific Yandex account.
	// * **serviceAccount:{service_account_id}**: A unique service account ID.
	// * **federatedUser:{federated_user_id}**: A unique federated user ID.
	// * **federatedUser:{federated_user_id}:**: A unique SAML federation user account ID.
	// * **group:{group_id}**: A unique group ID.
	// * **system:group:federation:{federation_id}:users**: All users in federation.
	// * **system:group:organization:{organization_id}:users**: All users in organization.
	// * **system:allAuthenticatedUsers**: All authenticated users.
	// * **system:allUsers**: All users, including unauthenticated ones.
	//
	// ~> for more information about system groups, see [Cloud Documentation](https://yandex.cloud/docs/iam/concepts/access-control/system-group).
	// +kubebuilder:validation:Optional
	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// (String) The role that should be assigned. Only one yandex_kubernetes_cluster_iam_member can be used per role.
	// The role that should be assigned. Only one yandex_kubernetes_cluster_iam_member can be used per role.
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (Number) For test purposes, to compensate IAM operations delay
	// For test purposes, to compensate IAM operations delay
	// +kubebuilder:validation:Optional
	SleepAfter *float64 `json:"sleepAfter,omitempty" tf:"sleep_after,omitempty"`
}

// ClusterIAMMemberSpec defines the desired state of ClusterIAMMember
type ClusterIAMMemberSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClusterIAMMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterIAMMemberInitParameters `json:"initProvider,omitempty"`
}

// ClusterIAMMemberStatus defines the observed state of ClusterIAMMember.
type ClusterIAMMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterIAMMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterIAMMember is the Schema for the ClusterIAMMembers API. Allows management of a single member for a single IAM binding for a Yandex Kubernetes cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,yandex-cloud}
type ClusterIAMMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	Spec   ClusterIAMMemberSpec   `json:"spec"`
	Status ClusterIAMMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterIAMMemberList contains a list of ClusterIAMMembers
type ClusterIAMMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterIAMMember `json:"items"`
}

// Repository type metadata.
var (
	ClusterIAMMember_Kind             = "ClusterIAMMember"
	ClusterIAMMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterIAMMember_Kind}.String()
	ClusterIAMMember_KindAPIVersion   = ClusterIAMMember_Kind + "." + CRDGroupVersion.String()
	ClusterIAMMember_GroupVersionKind = CRDGroupVersion.WithKind(ClusterIAMMember_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterIAMMember{}, &ClusterIAMMemberList{})
}
