apiVersion: mdb.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: ClickhouseCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhousecluster
  labels:
    testing.upbound.io/example-name: my_cluster
  name: my-cluster
  namespace: upbound-system
spec:
  forProvider:
    clickhouse:
    - config:
      - backgroundPoolSize: 16
        backgroundSchedulePoolSize: 16
        compression:
        - method: LZ4
          minPartSize: 1024
          minPartSizeRatio: 0.5
        - method: ZSTD
          minPartSize: 2048
          minPartSizeRatio: 0.7
        geobaseUri: ""
        graphiteRollup:
        - name: rollup1
          pattern:
          - function: func1
            regexp: abc
            retention:
            - age: 1000
              precision: 3
        - name: rollup2
          pattern:
          - function: func2
            retention:
            - age: 2000
              precision: 5
        kafka:
        - saslMechanism: SASL_MECHANISM_GSSAPI
          saslPasswordSecretRef:
            key: example-key
            name: example-secret
          saslUsername: user1
          securityProtocol: SECURITY_PROTOCOL_PLAINTEXT
        kafkaTopic:
        - name: topic1
          settings:
          - saslMechanism: SASL_MECHANISM_SCRAM_SHA_256
            saslPasswordSecretRef:
              key: example-key
              name: example-secret
            saslUsername: user2
            securityProtocol: SECURITY_PROTOCOL_SSL
        - name: topic2
          settings:
          - saslMechanism: SASL_MECHANISM_PLAIN
            securityProtocol: SECURITY_PROTOCOL_SASL_PLAINTEXT
        keepAliveTimeout: 3000
        logLevel: TRACE
        markCacheSize: 5368709120
        maxConcurrentQueries: 50
        maxConnections: 100
        maxPartitionSizeToDrop: 53687091200
        maxTableSizeToDrop: 53687091200
        mergeTree:
        - maxBytesToMergeAtMaxSpaceInPool: 161061273600
          maxBytesToMergeAtMinSpaceInPool: 1048576
          maxReplicatedMergesInQueue: 16
          numberOfFreeEntriesInPoolToLowerMaxSizeOfMerge: 8
          partsToDelayInsert: 150
          partsToThrowInsert: 300
          replicatedDeduplicationWindow: 100
          replicatedDeduplicationWindowSeconds: 604800
        metricLogEnabled: true
        metricLogRetentionSize: 536870912
        metricLogRetentionTime: 2592000
        partLogRetentionSize: 536870912
        partLogRetentionTime: 2592000
        queryLogRetentionSize: 1073741824
        queryLogRetentionTime: 2592000
        queryThreadLogEnabled: true
        queryThreadLogRetentionSize: 536870912
        queryThreadLogRetentionTime: 2592000
        rabbitmq:
        - passwordSecretRef:
            key: example-key
            name: example-secret
          username: rabbit_user
        textLogEnabled: true
        textLogLevel: TRACE
        textLogRetentionSize: 536870912
        textLogRetentionTime: 2592000
        timezone: UTC
        traceLogEnabled: true
        traceLogRetentionSize: 536870912
        traceLogRetentionTime: 2592000
        uncompressedCacheSize: 8589934592
      resources:
      - diskSize: 32
        diskTypeId: network-ssd
        resourcePresetId: s2.micro
    cloudStorage:
    - enabled: false
    database:
    - name: db_name
    environment: PRESTABLE
    formatSchema:
    - name: test_schema
      type: FORMAT_SCHEMA_TYPE_CAPNPROTO
      uri: https://storage.yandexcloud.net/ch-data/schema.proto
    host:
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
      type: CLICKHOUSE
      zone: ru-central1-a
    maintenanceWindow:
    - type: ANYTIME
    mlModel:
    - name: test_model
      type: ML_MODEL_TYPE_CATBOOST
      uri: https://storage.yandexcloud.net/ch-data/train.csv
    name: test
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    user:
    - name: user
      passwordSecretRef:
        key: example-key
        name: example-secret
      permission:
      - databaseName: db_name
      quota:
      - errors: 1000
        intervalDuration: 3600000
        queries: 10000
      - errors: 5000
        intervalDuration: 79800000
        queries: 50000
      settings:
      - maxMemoryUsageForUser: 1000000000
        outputFormatJsonQuote64BitIntegers: true
        readOverflowMode: throw

---

apiVersion: vpc.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhousecluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhousecluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.5.0.0/24
    zone: ru-central1-a
