apiVersion: mdb.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: MongodbCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mongodbcluster
  labels:
    testing.upbound.io/example-name: my_cluster
  name: my-cluster
  namespace: upbound-system
spec:
  forProvider:
    clusterConfig:
    - version: "4.2"
    database:
    - name: testdb
    environment: PRESTABLE
    host:
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
      zoneId: ru-central1-d
    labels:
      test_key: test_value
    maintenanceWindow:
    - type: ANYTIME
    name: test
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    resourcesMongocfg:
    - diskSize: 14
      diskTypeId: network-hdd
      resourcePresetId: s2.small
    resourcesMongod:
    - diskSize: 16
      diskTypeId: network-hdd
      resourcePresetId: s2.small
    resourcesMongos:
    - diskSize: 14
      diskTypeId: network-hdd
      resourcePresetId: s2.small
    user:
    - name: john
      passwordSecretRef:
        key: example-key
        name: example-secret
      permission:
      - databaseName: testdb

---

apiVersion: vpc.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mongodbcluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mongodbcluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.1.0.0/24
    zone: ru-central1-d
