apiVersion: backup.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: PolicyBindings
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policybindings
  labels:
    testing.upbound.io/example-name: test_backup_binding
  name: test-backup-binding
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_backup_compute
    policyId: ${data.yandex_backup_policy.test_backup_policy.id}

---

apiVersion: compute.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policybindings
  labels:
    testing.upbound.io/example-name: test_backup_compute
  name: test-backup-compute
spec:
  forProvider:
    bootDisk:
    - initializeParams:
      - imageIdSelector:
          matchLabels:
            testing.upbound.io/example-name: yandex_compute_image
    metadata:
      user-data: |
        #cloud-config
        packages:
          - curl
          - perl
          - jq
        runcmd:
          - curl https://storage.yandexcloud.net/backup-distributions/agent_installer.sh | sudo bash
    name: test-backup-compute
    networkInterface:
    - nat: true
      securityGroupIdsRefs:
      - name: test_backup_security_group
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_backup_subnet
    platformId: standard-v1
    resources:
    - cores: 2
      memory: 4
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_sa
    zone: ru-central1-a

---

apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policybindings
  labels:
    testing.upbound.io/example-name: test_sa
  name: test-sa
spec:
  forProvider: {}

---

apiVersion: resourcemanager.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: FolderIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policybindings
  labels:
    testing.upbound.io/example-name: test_binding
  name: test-binding
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_sa
    member: serviceAccount:${yandex_iam_service_account.test_sa.id}
    role: backup.editor

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policybindings
  labels:
    testing.upbound.io/example-name: test_backup_network
  name: test-backup-network
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policybindings
  labels:
    testing.upbound.io/example-name: test_backup_security_group
  name: test-backup-security-group
spec:
  forProvider:
    egress:
    - fromPort: 7770
      protocol: TCP
      toPort: 7800
      v4CidrBlocks:
      - 84.47.172.0/24
    - port: 443
      protocol: TCP
      v4CidrBlocks:
      - 213.180.204.0/24
      - 213.180.193.0/24
      - 178.176.128.0/24
      - 84.201.181.0/24
      - 84.47.172.0/24
    - port: 80
      protocol: TCP
      v4CidrBlocks:
      - 213.180.204.0/24
      - 213.180.193.0/24
    - port: 8443
      protocol: TCP
      v4CidrBlocks:
      - 84.47.172.0/24
    - port: 44445
      protocol: TCP
      v4CidrBlocks:
      - 51.250.1.0/24
    name: cloud-backup
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_backup_network

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/policybindings
  labels:
    testing.upbound.io/example-name: test_backup_subnet
  name: test-backup-subnet
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_backup_network
    v4CidrBlocks:
    - 192.168.0.0/24
    zone: ru-central1-a
