apiVersion: message.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: message/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: example_queue
  name: example-queue
spec:
  forProvider:
    messageRetentionSeconds: 1209600
    name: ymq_terraform_example
    receiveWaitTimeSeconds: 20
    redrivePolicy: |-
      ${jsonencode({
          deadLetterTargetArn = yandex_message_queue.example_deadletter_queue.arn
          maxReceiveCount     = 3
        })}
    visibilityTimeoutSeconds: 600
