apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ClickhouseUser
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhouseuser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    name: user
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    permission:
    - databaseNameSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
    quota:
    - errors: 1000
      intervalDuration: 3600000
      queries: 10000
    - errors: 5000
      intervalDuration: 79800000
      queries: 50000
    settings:
    - maxMemoryUsageForUser: 1000000000
      outputFormatJsonQuote64BitIntegers: true
      readOverflowMode: throw

---

apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ClickhouseCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhouseuser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    config:
    - {}
    environment: PRESTABLE
    host:
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
      type: CLICKHOUSE
      zone: ru-central1-a
    maintenanceWindow:
    - type: ANYTIME
    name: test
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    resources:
    - disk_size: 32
      disk_type_id: network-ssd
      resource_preset_id: s2.micro
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ClickhouseDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhouseuser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    name: database1

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhouseuser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/clickhouseuser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.5.0.0/24
    zone: ru-central1-a
