apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: GreenplumCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/greenplumcluster
  labels:
    testing.upbound.io/example-name: my_cluster
  name: my-cluster
spec:
  forProvider:
    access:
    - webSql: true
    assignPublicIp: true
    description: test greenplum cluster
    environment: PRESTABLE
    greenplumConfig:
      gp_add_column_inherits_table_setting: "true"
      gp_enable_global_deadlock_detector: "true"
      gp_global_deadlock_detector_period: 120
      gp_workfile_compression: "false"
      gp_workfile_limit_files_per_query: 100000
      gp_workfile_limit_per_query: 0
      gp_workfile_limit_per_segment: 0
      log_statement: 2
      max_connections: 395
      max_prepared_transactions: 500
      max_slot_wal_keep_size: 1048576
      max_statement_mem: 2147483648
    masterHostCount: 2
    masterSubcluster:
    - resources:
      - diskSize: 24
        diskTypeId: network-ssd
        resourcePresetId: s2.micro
    name: test
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    securityGroupIdsRefs:
    - name: test-sg-x
    segmentHostCount: 5
    segmentInHost: 1
    segmentSubcluster:
    - resources:
      - diskSize: 24
        diskTypeId: network-ssd
        resourcePresetId: s2.micro
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    userName: admin_user
    userPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    version: "6.28"
    zone_id: ru-central1-a

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/greenplumcluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/greenplumcluster
  labels:
    testing.upbound.io/example-name: test-sg-x
  name: test-sg-x
spec:
  forProvider:
    egress:
    - description: Allow outgoing traffic to members of the same security group
      fromPort: 0
      protocol: ANY
      toPort: 65535
      v4CidrBlocks:
      - 0.0.0.0/0
    ingress:
    - description: Allow incoming traffic from members of the same security group
      fromPort: 0
      protocol: ANY
      toPort: 65535
      v4CidrBlocks:
      - 0.0.0.0/0
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/greenplumcluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.5.0.0/24
    zone: ru-central1-a
