apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: MySQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqldatabase
  labels:
    testing.upbound.io/example-name: my_db
  name: my-db
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_cluster
    name: testdb

---

apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: MySQLCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqldatabase
  labels:
    testing.upbound.io/example-name: my_cluster
  name: my-cluster
spec:
  forProvider:
    environment: PRESTABLE
    host:
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
      zone: ru-central1-d
    name: test
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    resources:
    - diskSize: 16
      diskTypeId: network-ssd
      resourcePresetId: s2.micro
    version: "8.0"

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqldatabase
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqldatabase
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.5.0.0/24
    zone: ru-central1-d
