apiVersion: dns.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Recordset
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/recordset
  labels:
    testing.upbound.io/example-name: rs1
  name: rs1
spec:
  forProvider:
    data:
    - 10.1.0.1
    name: srv.example.com.
    ttl: 200
    type: A
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zone1

---

apiVersion: dns.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/recordset
  labels:
    testing.upbound.io/example-name: zone1
  name: zone1
spec:
  forProvider:
    description: desc
    labels:
      label1: label-1-value
    name: my_private_zone
    privateNetworksRefs:
    - name: foo
    public: false
    zone: example.com.

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/recordset
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}
