apiVersion: organizationmanager.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: GroupMembership
metadata:
  annotations:
    meta.upbound.io/example-id: organizationmanager/v1alpha1/groupmembership
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    members:
    - xdf********123
