//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnyFilterInitParameters) DeepCopyInto(out *AnyFilterInitParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnyFilterInitParameters.
func (in *AnyFilterInitParameters) DeepCopy() *AnyFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(AnyFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnyFilterObservation) DeepCopyInto(out *AnyFilterObservation) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnyFilterObservation.
func (in *AnyFilterObservation) DeepCopy() *AnyFilterObservation {
	if in == nil {
		return nil
	}
	out := new(AnyFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnyFilterParameters) DeepCopyInto(out *AnyFilterParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnyFilterParameters.
func (in *AnyFilterParameters) DeepCopy() *AnyFilterParameters {
	if in == nil {
		return nil
	}
	out := new(AnyFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnyFiltersInitParameters) DeepCopyInto(out *AnyFiltersInitParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnyFiltersInitParameters.
func (in *AnyFiltersInitParameters) DeepCopy() *AnyFiltersInitParameters {
	if in == nil {
		return nil
	}
	out := new(AnyFiltersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnyFiltersObservation) DeepCopyInto(out *AnyFiltersObservation) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnyFiltersObservation.
func (in *AnyFiltersObservation) DeepCopy() *AnyFiltersObservation {
	if in == nil {
		return nil
	}
	out := new(AnyFiltersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnyFiltersParameters) DeepCopyInto(out *AnyFiltersParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnyFiltersParameters.
func (in *AnyFiltersParameters) DeepCopy() *AnyFiltersParameters {
	if in == nil {
		return nil
	}
	out := new(AnyFiltersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoriesInitParameters) DeepCopyInto(out *CategoriesInitParameters) {
	*out = *in
	if in.Plane != nil {
		in, out := &in.Plane, &out.Plane
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoriesInitParameters.
func (in *CategoriesInitParameters) DeepCopy() *CategoriesInitParameters {
	if in == nil {
		return nil
	}
	out := new(CategoriesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoriesObservation) DeepCopyInto(out *CategoriesObservation) {
	*out = *in
	if in.Plane != nil {
		in, out := &in.Plane, &out.Plane
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoriesObservation.
func (in *CategoriesObservation) DeepCopy() *CategoriesObservation {
	if in == nil {
		return nil
	}
	out := new(CategoriesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoriesParameters) DeepCopyInto(out *CategoriesParameters) {
	*out = *in
	if in.Plane != nil {
		in, out := &in.Plane, &out.Plane
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoriesParameters.
func (in *CategoriesParameters) DeepCopy() *CategoriesParameters {
	if in == nil {
		return nil
	}
	out := new(CategoriesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStreamDestinationInitParameters) DeepCopyInto(out *DataStreamDestinationInitParameters) {
	*out = *in
	if in.DatabaseID != nil {
		in, out := &in.DatabaseID, &out.DatabaseID
		*out = new(string)
		**out = **in
	}
	if in.StreamName != nil {
		in, out := &in.StreamName, &out.StreamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStreamDestinationInitParameters.
func (in *DataStreamDestinationInitParameters) DeepCopy() *DataStreamDestinationInitParameters {
	if in == nil {
		return nil
	}
	out := new(DataStreamDestinationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStreamDestinationObservation) DeepCopyInto(out *DataStreamDestinationObservation) {
	*out = *in
	if in.DatabaseID != nil {
		in, out := &in.DatabaseID, &out.DatabaseID
		*out = new(string)
		**out = **in
	}
	if in.StreamName != nil {
		in, out := &in.StreamName, &out.StreamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStreamDestinationObservation.
func (in *DataStreamDestinationObservation) DeepCopy() *DataStreamDestinationObservation {
	if in == nil {
		return nil
	}
	out := new(DataStreamDestinationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStreamDestinationParameters) DeepCopyInto(out *DataStreamDestinationParameters) {
	*out = *in
	if in.DatabaseID != nil {
		in, out := &in.DatabaseID, &out.DatabaseID
		*out = new(string)
		**out = **in
	}
	if in.StreamName != nil {
		in, out := &in.StreamName, &out.StreamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStreamDestinationParameters.
func (in *DataStreamDestinationParameters) DeepCopy() *DataStreamDestinationParameters {
	if in == nil {
		return nil
	}
	out := new(DataStreamDestinationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventFiltersInitParameters) DeepCopyInto(out *EventFiltersInitParameters) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]CategoriesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PathFilter != nil {
		in, out := &in.PathFilter, &out.PathFilter
		*out = make([]PathFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventFiltersInitParameters.
func (in *EventFiltersInitParameters) DeepCopy() *EventFiltersInitParameters {
	if in == nil {
		return nil
	}
	out := new(EventFiltersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventFiltersObservation) DeepCopyInto(out *EventFiltersObservation) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]CategoriesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PathFilter != nil {
		in, out := &in.PathFilter, &out.PathFilter
		*out = make([]PathFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventFiltersObservation.
func (in *EventFiltersObservation) DeepCopy() *EventFiltersObservation {
	if in == nil {
		return nil
	}
	out := new(EventFiltersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventFiltersParameters) DeepCopyInto(out *EventFiltersParameters) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]CategoriesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PathFilter != nil {
		in, out := &in.PathFilter, &out.PathFilter
		*out = make([]PathFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventFiltersParameters.
func (in *EventFiltersParameters) DeepCopy() *EventFiltersParameters {
	if in == nil {
		return nil
	}
	out := new(EventFiltersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterInitParameters) DeepCopyInto(out *FilterInitParameters) {
	*out = *in
	if in.EventFilters != nil {
		in, out := &in.EventFilters, &out.EventFilters
		*out = make([]EventFiltersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PathFilter != nil {
		in, out := &in.PathFilter, &out.PathFilter
		*out = make([]FilterPathFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterInitParameters.
func (in *FilterInitParameters) DeepCopy() *FilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(FilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterObservation) DeepCopyInto(out *FilterObservation) {
	*out = *in
	if in.EventFilters != nil {
		in, out := &in.EventFilters, &out.EventFilters
		*out = make([]EventFiltersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PathFilter != nil {
		in, out := &in.PathFilter, &out.PathFilter
		*out = make([]FilterPathFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterObservation.
func (in *FilterObservation) DeepCopy() *FilterObservation {
	if in == nil {
		return nil
	}
	out := new(FilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterParameters) DeepCopyInto(out *FilterParameters) {
	*out = *in
	if in.EventFilters != nil {
		in, out := &in.EventFilters, &out.EventFilters
		*out = make([]EventFiltersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PathFilter != nil {
		in, out := &in.PathFilter, &out.PathFilter
		*out = make([]FilterPathFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterParameters.
func (in *FilterParameters) DeepCopy() *FilterParameters {
	if in == nil {
		return nil
	}
	out := new(FilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterPathFilterInitParameters) DeepCopyInto(out *FilterPathFilterInitParameters) {
	*out = *in
	if in.AnyFilter != nil {
		in, out := &in.AnyFilter, &out.AnyFilter
		*out = make([]PathFilterAnyFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SomeFilter != nil {
		in, out := &in.SomeFilter, &out.SomeFilter
		*out = make([]PathFilterSomeFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterPathFilterInitParameters.
func (in *FilterPathFilterInitParameters) DeepCopy() *FilterPathFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(FilterPathFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterPathFilterObservation) DeepCopyInto(out *FilterPathFilterObservation) {
	*out = *in
	if in.AnyFilter != nil {
		in, out := &in.AnyFilter, &out.AnyFilter
		*out = make([]PathFilterAnyFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SomeFilter != nil {
		in, out := &in.SomeFilter, &out.SomeFilter
		*out = make([]PathFilterSomeFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterPathFilterObservation.
func (in *FilterPathFilterObservation) DeepCopy() *FilterPathFilterObservation {
	if in == nil {
		return nil
	}
	out := new(FilterPathFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterPathFilterParameters) DeepCopyInto(out *FilterPathFilterParameters) {
	*out = *in
	if in.AnyFilter != nil {
		in, out := &in.AnyFilter, &out.AnyFilter
		*out = make([]PathFilterAnyFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SomeFilter != nil {
		in, out := &in.SomeFilter, &out.SomeFilter
		*out = make([]PathFilterSomeFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterPathFilterParameters.
func (in *FilterPathFilterParameters) DeepCopy() *FilterPathFilterParameters {
	if in == nil {
		return nil
	}
	out := new(FilterPathFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingDestinationInitParameters) DeepCopyInto(out *LoggingDestinationInitParameters) {
	*out = *in
	if in.LogGroupID != nil {
		in, out := &in.LogGroupID, &out.LogGroupID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingDestinationInitParameters.
func (in *LoggingDestinationInitParameters) DeepCopy() *LoggingDestinationInitParameters {
	if in == nil {
		return nil
	}
	out := new(LoggingDestinationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingDestinationObservation) DeepCopyInto(out *LoggingDestinationObservation) {
	*out = *in
	if in.LogGroupID != nil {
		in, out := &in.LogGroupID, &out.LogGroupID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingDestinationObservation.
func (in *LoggingDestinationObservation) DeepCopy() *LoggingDestinationObservation {
	if in == nil {
		return nil
	}
	out := new(LoggingDestinationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingDestinationParameters) DeepCopyInto(out *LoggingDestinationParameters) {
	*out = *in
	if in.LogGroupID != nil {
		in, out := &in.LogGroupID, &out.LogGroupID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingDestinationParameters.
func (in *LoggingDestinationParameters) DeepCopy() *LoggingDestinationParameters {
	if in == nil {
		return nil
	}
	out := new(LoggingDestinationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterAnyFilterInitParameters) DeepCopyInto(out *PathFilterAnyFilterInitParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterAnyFilterInitParameters.
func (in *PathFilterAnyFilterInitParameters) DeepCopy() *PathFilterAnyFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(PathFilterAnyFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterAnyFilterObservation) DeepCopyInto(out *PathFilterAnyFilterObservation) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterAnyFilterObservation.
func (in *PathFilterAnyFilterObservation) DeepCopy() *PathFilterAnyFilterObservation {
	if in == nil {
		return nil
	}
	out := new(PathFilterAnyFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterAnyFilterParameters) DeepCopyInto(out *PathFilterAnyFilterParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterAnyFilterParameters.
func (in *PathFilterAnyFilterParameters) DeepCopy() *PathFilterAnyFilterParameters {
	if in == nil {
		return nil
	}
	out := new(PathFilterAnyFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterInitParameters) DeepCopyInto(out *PathFilterInitParameters) {
	*out = *in
	if in.AnyFilter != nil {
		in, out := &in.AnyFilter, &out.AnyFilter
		*out = make([]AnyFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SomeFilter != nil {
		in, out := &in.SomeFilter, &out.SomeFilter
		*out = make([]SomeFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterInitParameters.
func (in *PathFilterInitParameters) DeepCopy() *PathFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(PathFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterObservation) DeepCopyInto(out *PathFilterObservation) {
	*out = *in
	if in.AnyFilter != nil {
		in, out := &in.AnyFilter, &out.AnyFilter
		*out = make([]AnyFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SomeFilter != nil {
		in, out := &in.SomeFilter, &out.SomeFilter
		*out = make([]SomeFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterObservation.
func (in *PathFilterObservation) DeepCopy() *PathFilterObservation {
	if in == nil {
		return nil
	}
	out := new(PathFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterParameters) DeepCopyInto(out *PathFilterParameters) {
	*out = *in
	if in.AnyFilter != nil {
		in, out := &in.AnyFilter, &out.AnyFilter
		*out = make([]AnyFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SomeFilter != nil {
		in, out := &in.SomeFilter, &out.SomeFilter
		*out = make([]SomeFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterParameters.
func (in *PathFilterParameters) DeepCopy() *PathFilterParameters {
	if in == nil {
		return nil
	}
	out := new(PathFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterSomeFilterInitParameters) DeepCopyInto(out *PathFilterSomeFilterInitParameters) {
	*out = *in
	if in.AnyFilters != nil {
		in, out := &in.AnyFilters, &out.AnyFilters
		*out = make([]SomeFilterAnyFiltersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterSomeFilterInitParameters.
func (in *PathFilterSomeFilterInitParameters) DeepCopy() *PathFilterSomeFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(PathFilterSomeFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterSomeFilterObservation) DeepCopyInto(out *PathFilterSomeFilterObservation) {
	*out = *in
	if in.AnyFilters != nil {
		in, out := &in.AnyFilters, &out.AnyFilters
		*out = make([]SomeFilterAnyFiltersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterSomeFilterObservation.
func (in *PathFilterSomeFilterObservation) DeepCopy() *PathFilterSomeFilterObservation {
	if in == nil {
		return nil
	}
	out := new(PathFilterSomeFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathFilterSomeFilterParameters) DeepCopyInto(out *PathFilterSomeFilterParameters) {
	*out = *in
	if in.AnyFilters != nil {
		in, out := &in.AnyFilters, &out.AnyFilters
		*out = make([]SomeFilterAnyFiltersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathFilterSomeFilterParameters.
func (in *PathFilterSomeFilterParameters) DeepCopy() *PathFilterSomeFilterParameters {
	if in == nil {
		return nil
	}
	out := new(PathFilterSomeFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SomeFilterAnyFiltersInitParameters) DeepCopyInto(out *SomeFilterAnyFiltersInitParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SomeFilterAnyFiltersInitParameters.
func (in *SomeFilterAnyFiltersInitParameters) DeepCopy() *SomeFilterAnyFiltersInitParameters {
	if in == nil {
		return nil
	}
	out := new(SomeFilterAnyFiltersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SomeFilterAnyFiltersObservation) DeepCopyInto(out *SomeFilterAnyFiltersObservation) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SomeFilterAnyFiltersObservation.
func (in *SomeFilterAnyFiltersObservation) DeepCopy() *SomeFilterAnyFiltersObservation {
	if in == nil {
		return nil
	}
	out := new(SomeFilterAnyFiltersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SomeFilterAnyFiltersParameters) DeepCopyInto(out *SomeFilterAnyFiltersParameters) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SomeFilterAnyFiltersParameters.
func (in *SomeFilterAnyFiltersParameters) DeepCopy() *SomeFilterAnyFiltersParameters {
	if in == nil {
		return nil
	}
	out := new(SomeFilterAnyFiltersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SomeFilterInitParameters) DeepCopyInto(out *SomeFilterInitParameters) {
	*out = *in
	if in.AnyFilters != nil {
		in, out := &in.AnyFilters, &out.AnyFilters
		*out = make([]AnyFiltersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SomeFilterInitParameters.
func (in *SomeFilterInitParameters) DeepCopy() *SomeFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(SomeFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SomeFilterObservation) DeepCopyInto(out *SomeFilterObservation) {
	*out = *in
	if in.AnyFilters != nil {
		in, out := &in.AnyFilters, &out.AnyFilters
		*out = make([]AnyFiltersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SomeFilterObservation.
func (in *SomeFilterObservation) DeepCopy() *SomeFilterObservation {
	if in == nil {
		return nil
	}
	out := new(SomeFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SomeFilterParameters) DeepCopyInto(out *SomeFilterParameters) {
	*out = *in
	if in.AnyFilters != nil {
		in, out := &in.AnyFilters, &out.AnyFilters
		*out = make([]AnyFiltersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SomeFilterParameters.
func (in *SomeFilterParameters) DeepCopy() *SomeFilterParameters {
	if in == nil {
		return nil
	}
	out := new(SomeFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDestinationInitParameters) DeepCopyInto(out *StorageDestinationInitParameters) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.ObjectPrefix != nil {
		in, out := &in.ObjectPrefix, &out.ObjectPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDestinationInitParameters.
func (in *StorageDestinationInitParameters) DeepCopy() *StorageDestinationInitParameters {
	if in == nil {
		return nil
	}
	out := new(StorageDestinationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDestinationObservation) DeepCopyInto(out *StorageDestinationObservation) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.ObjectPrefix != nil {
		in, out := &in.ObjectPrefix, &out.ObjectPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDestinationObservation.
func (in *StorageDestinationObservation) DeepCopy() *StorageDestinationObservation {
	if in == nil {
		return nil
	}
	out := new(StorageDestinationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDestinationParameters) DeepCopyInto(out *StorageDestinationParameters) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.ObjectPrefix != nil {
		in, out := &in.ObjectPrefix, &out.ObjectPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDestinationParameters.
func (in *StorageDestinationParameters) DeepCopy() *StorageDestinationParameters {
	if in == nil {
		return nil
	}
	out := new(StorageDestinationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrailsTrail) DeepCopyInto(out *TrailsTrail) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrailsTrail.
func (in *TrailsTrail) DeepCopy() *TrailsTrail {
	if in == nil {
		return nil
	}
	out := new(TrailsTrail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrailsTrail) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrailsTrailInitParameters) DeepCopyInto(out *TrailsTrailInitParameters) {
	*out = *in
	if in.DataStreamDestination != nil {
		in, out := &in.DataStreamDestination, &out.DataStreamDestination
		*out = make([]DataStreamDestinationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]FilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.FolderIDRef != nil {
		in, out := &in.FolderIDRef, &out.FolderIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FolderIDSelector != nil {
		in, out := &in.FolderIDSelector, &out.FolderIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LoggingDestination != nil {
		in, out := &in.LoggingDestination, &out.LoggingDestination
		*out = make([]LoggingDestinationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountID != nil {
		in, out := &in.ServiceAccountID, &out.ServiceAccountID
		*out = new(string)
		**out = **in
	}
	if in.StorageDestination != nil {
		in, out := &in.StorageDestination, &out.StorageDestination
		*out = make([]StorageDestinationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrailsTrailInitParameters.
func (in *TrailsTrailInitParameters) DeepCopy() *TrailsTrailInitParameters {
	if in == nil {
		return nil
	}
	out := new(TrailsTrailInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrailsTrailList) DeepCopyInto(out *TrailsTrailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrailsTrail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrailsTrailList.
func (in *TrailsTrailList) DeepCopy() *TrailsTrailList {
	if in == nil {
		return nil
	}
	out := new(TrailsTrailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrailsTrailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrailsTrailObservation) DeepCopyInto(out *TrailsTrailObservation) {
	*out = *in
	if in.DataStreamDestination != nil {
		in, out := &in.DataStreamDestination, &out.DataStreamDestination
		*out = make([]DataStreamDestinationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]FilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LoggingDestination != nil {
		in, out := &in.LoggingDestination, &out.LoggingDestination
		*out = make([]LoggingDestinationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountID != nil {
		in, out := &in.ServiceAccountID, &out.ServiceAccountID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StorageDestination != nil {
		in, out := &in.StorageDestination, &out.StorageDestination
		*out = make([]StorageDestinationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrailID != nil {
		in, out := &in.TrailID, &out.TrailID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrailsTrailObservation.
func (in *TrailsTrailObservation) DeepCopy() *TrailsTrailObservation {
	if in == nil {
		return nil
	}
	out := new(TrailsTrailObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrailsTrailParameters) DeepCopyInto(out *TrailsTrailParameters) {
	*out = *in
	if in.DataStreamDestination != nil {
		in, out := &in.DataStreamDestination, &out.DataStreamDestination
		*out = make([]DataStreamDestinationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]FilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.FolderIDRef != nil {
		in, out := &in.FolderIDRef, &out.FolderIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FolderIDSelector != nil {
		in, out := &in.FolderIDSelector, &out.FolderIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LoggingDestination != nil {
		in, out := &in.LoggingDestination, &out.LoggingDestination
		*out = make([]LoggingDestinationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountID != nil {
		in, out := &in.ServiceAccountID, &out.ServiceAccountID
		*out = new(string)
		**out = **in
	}
	if in.StorageDestination != nil {
		in, out := &in.StorageDestination, &out.StorageDestination
		*out = make([]StorageDestinationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrailsTrailParameters.
func (in *TrailsTrailParameters) DeepCopy() *TrailsTrailParameters {
	if in == nil {
		return nil
	}
	out := new(TrailsTrailParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrailsTrailSpec) DeepCopyInto(out *TrailsTrailSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrailsTrailSpec.
func (in *TrailsTrailSpec) DeepCopy() *TrailsTrailSpec {
	if in == nil {
		return nil
	}
	out := new(TrailsTrailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrailsTrailStatus) DeepCopyInto(out *TrailsTrailStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrailsTrailStatus.
func (in *TrailsTrailStatus) DeepCopy() *TrailsTrailStatus {
	if in == nil {
		return nil
	}
	out := new(TrailsTrailStatus)
	in.DeepCopyInto(out)
	return out
}
