apiVersion: storage.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    bucket: tf-test-bucket
