apiVersion: storage.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessKeySelector:
      matchLabels:
        testing.upbound.io/example-name: sa-static-key
    bucket: tf-test-bucket
    secretKeySecretRef:
      key: attribute.secret_key
      name: example-iam-service-account-static-access-key
      namespace: upbound-system

---

apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: sa
  name: sa
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: iam.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: ServiceAccountStaticAccessKey
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: sa-static-key
  name: sa-static-key
spec:
  forProvider:
    description: static access key for object storage
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sa

---

apiVersion: resourcemanager.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: FolderIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: sa-editor
  name: sa-editor
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    member: serviceAccount:${yandex_iam_service_account.sa.id}
    role: storage.editor
