apiVersion: function.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: IAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: function/v1alpha1/iambinding
  labels:
    testing.upbound.io/example-name: function-iam
  name: function-iam
spec:
  forProvider:
    functionId: your-function-id
    members:
    - system:allUsers
    role: serverless.functions.invoker
