apiVersion: kms.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: SecretCiphertext
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/secretciphertext
  labels:
    testing.upbound.io/example-name: password
  name: password
spec:
  forProvider:
    aadContext: additional authenticated data
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    plaintextSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: kms.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: SymmetricKey
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/secretciphertext
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: description for key
    name: example-symetric-key
