// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConsumerInitParameters struct {

	// : Changefeed name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Timestamp in the UNIX timestamp format, from which the consumer will start reading data
	StartingMessageTimestampMs *float64 `json:"startingMessageTimestampMs,omitempty" tf:"starting_message_timestamp_ms,omitempty"`

	// Supported data encodings
	// +listType=set
	SupportedCodecs []*string `json:"supportedCodecs,omitempty" tf:"supported_codecs,omitempty"`
}

type ConsumerObservation struct {

	// : Changefeed name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Timestamp in the UNIX timestamp format, from which the consumer will start reading data
	StartingMessageTimestampMs *float64 `json:"startingMessageTimestampMs,omitempty" tf:"starting_message_timestamp_ms,omitempty"`

	// Supported data encodings
	// +listType=set
	SupportedCodecs []*string `json:"supportedCodecs,omitempty" tf:"supported_codecs,omitempty"`
}

type ConsumerParameters struct {

	// : Changefeed name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Timestamp in the UNIX timestamp format, from which the consumer will start reading data
	// +kubebuilder:validation:Optional
	StartingMessageTimestampMs *float64 `json:"startingMessageTimestampMs,omitempty" tf:"starting_message_timestamp_ms,omitempty"`

	// Supported data encodings
	// +kubebuilder:validation:Optional
	// +listType=set
	SupportedCodecs []*string `json:"supportedCodecs,omitempty" tf:"supported_codecs,omitempty"`
}

type TableChangefeedInitParameters struct {

	// Connection string, conflicts with table_id
	ConnectionString *string `json:"connectionString,omitempty" tf:"connection_string,omitempty"`

	// Changefeed consumers - named entities for reading data from the topic.
	Consumer []ConsumerInitParameters `json:"consumer,omitempty" tf:"consumer,omitempty"`

	// : Changefeed format. Only JSON format is available.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// : Changefeed operating mode. The available changefeed operating modes are presented in the documentation.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// : Changefeed name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Time of data retention in the topic, ISO 8601 format
	RetentionPeriod *string `json:"retentionPeriod,omitempty" tf:"retention_period,omitempty"`

	// : ID of the table for which we create the changefeed.
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`

	// Table path
	TablePath *string `json:"tablePath,omitempty" tf:"table_path,omitempty"`

	// Use virtual timestamps
	VirtualTimestamps *bool `json:"virtualTimestamps,omitempty" tf:"virtual_timestamps,omitempty"`
}

type TableChangefeedObservation struct {

	// Connection string, conflicts with table_id
	ConnectionString *string `json:"connectionString,omitempty" tf:"connection_string,omitempty"`

	// Changefeed consumers - named entities for reading data from the topic.
	Consumer []ConsumerObservation `json:"consumer,omitempty" tf:"consumer,omitempty"`

	// : Changefeed format. Only JSON format is available.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// : Changefeed operating mode. The available changefeed operating modes are presented in the documentation.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// : Changefeed name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Time of data retention in the topic, ISO 8601 format
	RetentionPeriod *string `json:"retentionPeriod,omitempty" tf:"retention_period,omitempty"`

	// : ID of the table for which we create the changefeed.
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`

	// Table path
	TablePath *string `json:"tablePath,omitempty" tf:"table_path,omitempty"`

	// Use virtual timestamps
	VirtualTimestamps *bool `json:"virtualTimestamps,omitempty" tf:"virtual_timestamps,omitempty"`
}

type TableChangefeedParameters struct {

	// Connection string, conflicts with table_id
	// +kubebuilder:validation:Optional
	ConnectionString *string `json:"connectionString,omitempty" tf:"connection_string,omitempty"`

	// Changefeed consumers - named entities for reading data from the topic.
	// +kubebuilder:validation:Optional
	Consumer []ConsumerParameters `json:"consumer,omitempty" tf:"consumer,omitempty"`

	// : Changefeed format. Only JSON format is available.
	// +kubebuilder:validation:Optional
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// : Changefeed operating mode. The available changefeed operating modes are presented in the documentation.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// : Changefeed name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Time of data retention in the topic, ISO 8601 format
	// +kubebuilder:validation:Optional
	RetentionPeriod *string `json:"retentionPeriod,omitempty" tf:"retention_period,omitempty"`

	// : ID of the table for which we create the changefeed.
	// +kubebuilder:validation:Optional
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`

	// Table path
	// +kubebuilder:validation:Optional
	TablePath *string `json:"tablePath,omitempty" tf:"table_path,omitempty"`

	// Use virtual timestamps
	// +kubebuilder:validation:Optional
	VirtualTimestamps *bool `json:"virtualTimestamps,omitempty" tf:"virtual_timestamps,omitempty"`
}

// TableChangefeedSpec defines the desired state of TableChangefeed
type TableChangefeedSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TableChangefeedParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TableChangefeedInitParameters `json:"initProvider,omitempty"`
}

// TableChangefeedStatus defines the observed state of TableChangefeed.
type TableChangefeedStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TableChangefeedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TableChangefeed is the Schema for the TableChangefeeds API. Manages Yandex Database dedicated cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,yandex-cloud}
type TableChangefeed struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.format) || (has(self.initProvider) && has(self.initProvider.format))",message="spec.forProvider.format is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mode) || (has(self.initProvider) && has(self.initProvider.mode))",message="spec.forProvider.mode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TableChangefeedSpec   `json:"spec"`
	Status TableChangefeedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TableChangefeedList contains a list of TableChangefeeds
type TableChangefeedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TableChangefeed `json:"items"`
}

// Repository type metadata.
var (
	TableChangefeed_Kind             = "TableChangefeed"
	TableChangefeed_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TableChangefeed_Kind}.String()
	TableChangefeed_KindAPIVersion   = TableChangefeed_Kind + "." + CRDGroupVersion.String()
	TableChangefeed_GroupVersionKind = CRDGroupVersion.WithKind(TableChangefeed_Kind)
)

func init() {
	SchemeBuilder.Register(&TableChangefeed{}, &TableChangefeedList{})
}
