apiVersion: audit.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: TrailsTrail
metadata:
  annotations:
    meta.upbound.io/example-id: audit/v1alpha1/trailstrail
  labels:
    testing.upbound.io/example-name: basic_trail
  name: basic-trail
  namespace: upbound-system
spec:
  forProvider:
    description: Some trail description
    filter:
    - eventFilters:
      - categories:
        - plane: DATA_PLANE
          type: WRITE
        pathFilter:
        - anyFilter:
          - resourceId: home-folder
            resourceType: resource-manager.folder
        service: storage
      - categories:
        - plane: DATA_PLANE
          type: READ
        pathFilter:
        - someFilter:
          - anyFilters:
            - resourceId: vpc-net-id-1
              resourceType: vpc.network
            - resourceId: vpc-net-id-2
              resourceType: vpc.network
            resourceId: home-folder
            resourceType: resource-manager.folder
        service: dns
      pathFilter:
      - anyFilter:
        - resourceId: home-folder
          resourceType: resource-manager.folder
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    labels:
      key: value
    loggingDestination:
    - logGroupId: some-log-group
    name: a-trail
    serviceAccountId: trail-service-account
