apiVersion: function.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: ScalingPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: function/v1alpha1/scalingpolicy
  labels:
    testing.upbound.io/example-name: my_scaling_policy
  name: my-scaling-policy
  namespace: upbound-system
spec:
  forProvider:
    functionId: are1samplefunction11
    policy:
    - tag: $latest
      zoneInstancesLimit: 3
      zoneRequestsLimit: 100
    - tag: my_tag
      zoneInstancesLimit: 4
      zoneRequestsLimit: 150
