apiVersion: lockbox.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: SecretIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: lockbox/v1alpha1/secretiammember
  labels:
    testing.upbound.io/example-name: viewer
  name: viewer
  namespace: upbound-system
spec:
  forProvider:
    member: userAccount:foo_user_id
    role: viewer
    secretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: your-secret

---

apiVersion: lockbox.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: lockbox/v1alpha1/secretiammember
  labels:
    testing.upbound.io/example-name: your-secret
  name: your-secret
  namespace: upbound-system
spec:
  forProvider:
    name: secret-name
