apiVersion: lockbox.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: SecretIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: lockbox/v1alpha1/secretiambinding
  labels:
    testing.upbound.io/example-name: viewer
  name: viewer
  namespace: upbound-system
spec:
  forProvider:
    role: viewer
    secretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: your-secret
    serviceAccountRef:
    - name: example

---

apiVersion: lockbox.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: lockbox/v1alpha1/secretiambinding
  labels:
    testing.upbound.io/example-name: your-secret
  name: your-secret
  namespace: upbound-system
spec:
  forProvider:
    name: secret-name
