apiVersion: lockbox.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: lockbox/v1alpha1/secretversion
  labels:
    testing.upbound.io/example-name: my_version
  name: my-version
  namespace: upbound-system
spec:
  forProvider:
    entries:
    - key: key1
      textValueSecretRef:
        key: example-key
        name: example-secret
    - command:
      - path: my_secret_generator.sh
      key: k2
    secretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_secret

---

apiVersion: lockbox.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: lockbox/v1alpha1/secretversion
  labels:
    testing.upbound.io/example-name: my_secret
  name: my-secret
  namespace: upbound-system
spec:
  forProvider:
    name: test secret
