// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ModulesInitParameters struct {

	// (Attributes) Valkey bloom module settings. (see below for nested schema)
	ValkeyBloom *ValkeyBloomInitParameters `json:"valkeyBloom,omitempty" tf:"valkey_bloom,omitempty"`

	// (Attributes) Valkey json module settings. (see below for nested schema)
	ValkeyJSON *ValkeyJSONInitParameters `json:"valkeyJson,omitempty" tf:"valkey_json,omitempty"`

	// (Attributes) Valkey search module settings. (see below for nested schema)
	ValkeySearch *ValkeySearchInitParameters `json:"valkeySearch,omitempty" tf:"valkey_search,omitempty"`
}

type ModulesObservation struct {

	// (Attributes) Valkey bloom module settings. (see below for nested schema)
	ValkeyBloom *ValkeyBloomObservation `json:"valkeyBloom,omitempty" tf:"valkey_bloom,omitempty"`

	// (Attributes) Valkey json module settings. (see below for nested schema)
	ValkeyJSON *ValkeyJSONObservation `json:"valkeyJson,omitempty" tf:"valkey_json,omitempty"`

	// (Attributes) Valkey search module settings. (see below for nested schema)
	ValkeySearch *ValkeySearchObservation `json:"valkeySearch,omitempty" tf:"valkey_search,omitempty"`
}

type ModulesParameters struct {

	// (Attributes) Valkey bloom module settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ValkeyBloom *ValkeyBloomParameters `json:"valkeyBloom,omitempty" tf:"valkey_bloom,omitempty"`

	// (Attributes) Valkey json module settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ValkeyJSON *ValkeyJSONParameters `json:"valkeyJson,omitempty" tf:"valkey_json,omitempty"`

	// (Attributes) Valkey search module settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ValkeySearch *ValkeySearchParameters `json:"valkeySearch,omitempty" tf:"valkey_search,omitempty"`
}

type RedisClusterV2AccessInitParameters struct {

	// (Boolean) Allow access for Yandex DataLens. Can be either true or false.
	// Allow access for Yandex DataLens. Can be either true or false.
	DataLens *bool `json:"dataLens,omitempty" tf:"data_lens,omitempty"`

	// (Boolean) Allow access for SQL queries in the management console. Can be either true or false.
	// Allow access for SQL queries in the management console. Can be either true or false.
	WebSQL *bool `json:"webSql,omitempty" tf:"web_sql,omitempty"`
}

type RedisClusterV2AccessObservation struct {

	// (Boolean) Allow access for Yandex DataLens. Can be either true or false.
	// Allow access for Yandex DataLens. Can be either true or false.
	DataLens *bool `json:"dataLens,omitempty" tf:"data_lens,omitempty"`

	// (Boolean) Allow access for SQL queries in the management console. Can be either true or false.
	// Allow access for SQL queries in the management console. Can be either true or false.
	WebSQL *bool `json:"webSql,omitempty" tf:"web_sql,omitempty"`
}

type RedisClusterV2AccessParameters struct {

	// (Boolean) Allow access for Yandex DataLens. Can be either true or false.
	// Allow access for Yandex DataLens. Can be either true or false.
	// +kubebuilder:validation:Optional
	DataLens *bool `json:"dataLens,omitempty" tf:"data_lens,omitempty"`

	// (Boolean) Allow access for SQL queries in the management console. Can be either true or false.
	// Allow access for SQL queries in the management console. Can be either true or false.
	// +kubebuilder:validation:Optional
	WebSQL *bool `json:"webSql,omitempty" tf:"web_sql,omitempty"`
}

type RedisClusterV2ConfigBackupWindowStartInitParameters struct {

	// (Number) The hour at which backup will be started.
	// The hour at which backup will be started.
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (Number) The minute at which backup will be started.
	// The minute at which backup will be started.
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type RedisClusterV2ConfigBackupWindowStartObservation struct {

	// (Number) The hour at which backup will be started.
	// The hour at which backup will be started.
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (Number) The minute at which backup will be started.
	// The minute at which backup will be started.
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type RedisClusterV2ConfigBackupWindowStartParameters struct {

	// (Number) The hour at which backup will be started.
	// The hour at which backup will be started.
	// +kubebuilder:validation:Optional
	Hours *float64 `json:"hours" tf:"hours,omitempty"`

	// (Number) The minute at which backup will be started.
	// The minute at which backup will be started.
	// +kubebuilder:validation:Optional
	Minutes *float64 `json:"minutes" tf:"minutes,omitempty"`
}

type RedisClusterV2ConfigInitParameters struct {

	// (Boolean) Allows some data to be lost in favor of faster switchover/restart. Can be either true or false.
	// Allows some data to be lost in favor of faster switchover/restart. Can be either true or false.
	AllowDataLoss *bool `json:"allowDataLoss,omitempty" tf:"allow_data_loss,omitempty"`

	// (Number) Retain period of automatically created backup in days.
	// Retain period of automatically created backup in days.
	BackupRetainPeriodDays *float64 `json:"backupRetainPeriodDays,omitempty" tf:"backup_retain_period_days,omitempty"`

	// (Attributes) Time to start the daily backup, in the UTC timezone. (see below for nested schema)
	BackupWindowStart *RedisClusterV2ConfigBackupWindowStartInitParameters `json:"backupWindowStart,omitempty" tf:"backup_window_start,omitempty"`

	// (String) Redis connection output buffers limits for clients.
	// Redis connection output buffers limits for clients.
	ClientOutputBufferLimitNormal *string `json:"clientOutputBufferLimitNormal,omitempty" tf:"client_output_buffer_limit_normal,omitempty"`

	// (String) Redis connection output buffers limits for pubsub operations.
	// Redis connection output buffers limits for pubsub operations.
	ClientOutputBufferLimitPubsub *string `json:"clientOutputBufferLimitPubsub,omitempty" tf:"client_output_buffer_limit_pubsub,omitempty"`

	// (Boolean) Permits Pub/Sub shard operations when cluster is down. Can be either true or false.
	// Permits Pub/Sub shard operations when cluster is down. Can be either true or false.
	ClusterAllowPubsubshardWhenDown *bool `json:"clusterAllowPubsubshardWhenDown,omitempty" tf:"cluster_allow_pubsubshard_when_down,omitempty"`

	// (Boolean) Allows read operations when cluster is down. Can be either true or false.
	// Allows read operations when cluster is down. Can be either true or false.
	ClusterAllowReadsWhenDown *bool `json:"clusterAllowReadsWhenDown,omitempty" tf:"cluster_allow_reads_when_down,omitempty"`

	// (Boolean) Controls whether all hash slots must be covered by nodes. Can be either true or false.
	// Controls whether all hash slots must be covered by nodes. Can be either true or false.
	ClusterRequireFullCoverage *bool `json:"clusterRequireFullCoverage,omitempty" tf:"cluster_require_full_coverage,omitempty"`

	// server process.
	// Number of database buckets on a single redis-server process.
	Databases *float64 `json:"databases,omitempty" tf:"databases,omitempty"`

	// threads. Can be either true or false.
	// Allow redis to use io-threads. Can be either true or false.
	IoThreadsAllowed *bool `json:"ioThreadsAllowed,omitempty" tf:"io_threads_allowed,omitempty"`

	// (Number) The time, in minutes, that must elapse in order for the key counter to be divided by two (or decremented if it has a value less <= 10).
	// The time, in minutes, that must elapse in order for the key counter to be divided by two (or decremented if it has a value less <= 10).
	LfuDecayTime *float64 `json:"lfuDecayTime,omitempty" tf:"lfu_decay_time,omitempty"`

	// (Number) Determines how the frequency counter represents key hits.
	// Determines how the frequency counter represents key hits.
	LfuLogFactor *float64 `json:"lfuLogFactor,omitempty" tf:"lfu_log_factor,omitempty"`

	// disabled mechanism.
	// Maximum time in milliseconds for Lua scripts, 0 - disabled mechanism.
	LuaTimeLimit *float64 `json:"luaTimeLimit,omitempty" tf:"lua_time_limit,omitempty"`

	// (Number) Redis maxmemory percent
	// Redis maxmemory percent
	MaxmemoryPercent *float64 `json:"maxmemoryPercent,omitempty" tf:"maxmemory_percent,omitempty"`

	// (String) Redis key eviction policy for a dataset that reaches maximum memory, available to the host.
	// Redis key eviction policy for a dataset that reaches maximum memory, available to the host.
	MaxmemoryPolicy *string `json:"maxmemoryPolicy,omitempty" tf:"maxmemory_policy,omitempty"`

	// (String) String setting for pub\sub functionality.
	// String setting for pub\sub functionality.
	NotifyKeyspaceEvents *string `json:"notifyKeyspaceEvents,omitempty" tf:"notify_keyspace_events,omitempty"`

	// (String, Sensitive) Authentication password.
	// Authentication password.
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Number) Replication backlog size as a percentage of flavor maxmemory.
	// Replication backlog size as a percentage of flavor maxmemory.
	ReplBacklogSizePercent *float64 `json:"replBacklogSizePercent,omitempty" tf:"repl_backlog_size_percent,omitempty"`

	// (Number) Threshold for logging slow requests to server in microseconds (log only slower than it).
	// Threshold for logging slow requests to server in microseconds (log only slower than it).
	SlowlogLogSlowerThan *float64 `json:"slowlogLogSlowerThan,omitempty" tf:"slowlog_log_slower_than,omitempty"`

	// (Number) Max slow requests number to log.
	// Max slow requests number to log.
	SlowlogMaxLen *float64 `json:"slowlogMaxLen,omitempty" tf:"slowlog_max_len,omitempty"`

	// (Number) Time that Redis keeps the connection open while the client is idle.
	// Time that Redis keeps the connection open while the client is idle.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (Boolean) Allows to turn before switchover in RDSync. Can be either true or false.
	// Allows to turn before switchover in RDSync. Can be either true or false.
	TurnBeforeSwitchover *bool `json:"turnBeforeSwitchover,omitempty" tf:"turn_before_switchover,omitempty"`

	// (Boolean) Use JIT for lua scripts and functions. Can be either true or false.
	// Use JIT for lua scripts and functions. Can be either true or false.
	UseLuajit *bool `json:"useLuajit,omitempty" tf:"use_luajit,omitempty"`

	// (String) Redis version.
	// Redis version.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// efficient listpack to CPU-efficient hash table and skiplist
	// Controls max number of entries in zset before conversion from memory-efficient listpack to CPU-efficient hash table and skiplist
	ZsetMaxListpackEntries *float64 `json:"zsetMaxListpackEntries,omitempty" tf:"zset_max_listpack_entries,omitempty"`
}

type RedisClusterV2ConfigObservation struct {

	// (Boolean) Allows some data to be lost in favor of faster switchover/restart. Can be either true or false.
	// Allows some data to be lost in favor of faster switchover/restart. Can be either true or false.
	AllowDataLoss *bool `json:"allowDataLoss,omitempty" tf:"allow_data_loss,omitempty"`

	// (Number) Retain period of automatically created backup in days.
	// Retain period of automatically created backup in days.
	BackupRetainPeriodDays *float64 `json:"backupRetainPeriodDays,omitempty" tf:"backup_retain_period_days,omitempty"`

	// (Attributes) Time to start the daily backup, in the UTC timezone. (see below for nested schema)
	BackupWindowStart *RedisClusterV2ConfigBackupWindowStartObservation `json:"backupWindowStart,omitempty" tf:"backup_window_start,omitempty"`

	// (String) Redis connection output buffers limits for clients.
	// Redis connection output buffers limits for clients.
	ClientOutputBufferLimitNormal *string `json:"clientOutputBufferLimitNormal,omitempty" tf:"client_output_buffer_limit_normal,omitempty"`

	// (String) Redis connection output buffers limits for pubsub operations.
	// Redis connection output buffers limits for pubsub operations.
	ClientOutputBufferLimitPubsub *string `json:"clientOutputBufferLimitPubsub,omitempty" tf:"client_output_buffer_limit_pubsub,omitempty"`

	// (Boolean) Permits Pub/Sub shard operations when cluster is down. Can be either true or false.
	// Permits Pub/Sub shard operations when cluster is down. Can be either true or false.
	ClusterAllowPubsubshardWhenDown *bool `json:"clusterAllowPubsubshardWhenDown,omitempty" tf:"cluster_allow_pubsubshard_when_down,omitempty"`

	// (Boolean) Allows read operations when cluster is down. Can be either true or false.
	// Allows read operations when cluster is down. Can be either true or false.
	ClusterAllowReadsWhenDown *bool `json:"clusterAllowReadsWhenDown,omitempty" tf:"cluster_allow_reads_when_down,omitempty"`

	// (Boolean) Controls whether all hash slots must be covered by nodes. Can be either true or false.
	// Controls whether all hash slots must be covered by nodes. Can be either true or false.
	ClusterRequireFullCoverage *bool `json:"clusterRequireFullCoverage,omitempty" tf:"cluster_require_full_coverage,omitempty"`

	// server process.
	// Number of database buckets on a single redis-server process.
	Databases *float64 `json:"databases,omitempty" tf:"databases,omitempty"`

	// threads. Can be either true or false.
	// Allow redis to use io-threads. Can be either true or false.
	IoThreadsAllowed *bool `json:"ioThreadsAllowed,omitempty" tf:"io_threads_allowed,omitempty"`

	// (Number) The time, in minutes, that must elapse in order for the key counter to be divided by two (or decremented if it has a value less <= 10).
	// The time, in minutes, that must elapse in order for the key counter to be divided by two (or decremented if it has a value less <= 10).
	LfuDecayTime *float64 `json:"lfuDecayTime,omitempty" tf:"lfu_decay_time,omitempty"`

	// (Number) Determines how the frequency counter represents key hits.
	// Determines how the frequency counter represents key hits.
	LfuLogFactor *float64 `json:"lfuLogFactor,omitempty" tf:"lfu_log_factor,omitempty"`

	// disabled mechanism.
	// Maximum time in milliseconds for Lua scripts, 0 - disabled mechanism.
	LuaTimeLimit *float64 `json:"luaTimeLimit,omitempty" tf:"lua_time_limit,omitempty"`

	// (Number) Redis maxmemory percent
	// Redis maxmemory percent
	MaxmemoryPercent *float64 `json:"maxmemoryPercent,omitempty" tf:"maxmemory_percent,omitempty"`

	// (String) Redis key eviction policy for a dataset that reaches maximum memory, available to the host.
	// Redis key eviction policy for a dataset that reaches maximum memory, available to the host.
	MaxmemoryPolicy *string `json:"maxmemoryPolicy,omitempty" tf:"maxmemory_policy,omitempty"`

	// (String) String setting for pub\sub functionality.
	// String setting for pub\sub functionality.
	NotifyKeyspaceEvents *string `json:"notifyKeyspaceEvents,omitempty" tf:"notify_keyspace_events,omitempty"`

	// (Number) Replication backlog size as a percentage of flavor maxmemory.
	// Replication backlog size as a percentage of flavor maxmemory.
	ReplBacklogSizePercent *float64 `json:"replBacklogSizePercent,omitempty" tf:"repl_backlog_size_percent,omitempty"`

	// (Number) Threshold for logging slow requests to server in microseconds (log only slower than it).
	// Threshold for logging slow requests to server in microseconds (log only slower than it).
	SlowlogLogSlowerThan *float64 `json:"slowlogLogSlowerThan,omitempty" tf:"slowlog_log_slower_than,omitempty"`

	// (Number) Max slow requests number to log.
	// Max slow requests number to log.
	SlowlogMaxLen *float64 `json:"slowlogMaxLen,omitempty" tf:"slowlog_max_len,omitempty"`

	// (Number) Time that Redis keeps the connection open while the client is idle.
	// Time that Redis keeps the connection open while the client is idle.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (Boolean) Allows to turn before switchover in RDSync. Can be either true or false.
	// Allows to turn before switchover in RDSync. Can be either true or false.
	TurnBeforeSwitchover *bool `json:"turnBeforeSwitchover,omitempty" tf:"turn_before_switchover,omitempty"`

	// (Boolean) Use JIT for lua scripts and functions. Can be either true or false.
	// Use JIT for lua scripts and functions. Can be either true or false.
	UseLuajit *bool `json:"useLuajit,omitempty" tf:"use_luajit,omitempty"`

	// (String) Redis version.
	// Redis version.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// efficient listpack to CPU-efficient hash table and skiplist
	// Controls max number of entries in zset before conversion from memory-efficient listpack to CPU-efficient hash table and skiplist
	ZsetMaxListpackEntries *float64 `json:"zsetMaxListpackEntries,omitempty" tf:"zset_max_listpack_entries,omitempty"`
}

type RedisClusterV2ConfigParameters struct {

	// (Boolean) Allows some data to be lost in favor of faster switchover/restart. Can be either true or false.
	// Allows some data to be lost in favor of faster switchover/restart. Can be either true or false.
	// +kubebuilder:validation:Optional
	AllowDataLoss *bool `json:"allowDataLoss,omitempty" tf:"allow_data_loss,omitempty"`

	// (Number) Retain period of automatically created backup in days.
	// Retain period of automatically created backup in days.
	// +kubebuilder:validation:Optional
	BackupRetainPeriodDays *float64 `json:"backupRetainPeriodDays,omitempty" tf:"backup_retain_period_days,omitempty"`

	// (Attributes) Time to start the daily backup, in the UTC timezone. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BackupWindowStart *RedisClusterV2ConfigBackupWindowStartParameters `json:"backupWindowStart,omitempty" tf:"backup_window_start,omitempty"`

	// (String) Redis connection output buffers limits for clients.
	// Redis connection output buffers limits for clients.
	// +kubebuilder:validation:Optional
	ClientOutputBufferLimitNormal *string `json:"clientOutputBufferLimitNormal,omitempty" tf:"client_output_buffer_limit_normal,omitempty"`

	// (String) Redis connection output buffers limits for pubsub operations.
	// Redis connection output buffers limits for pubsub operations.
	// +kubebuilder:validation:Optional
	ClientOutputBufferLimitPubsub *string `json:"clientOutputBufferLimitPubsub,omitempty" tf:"client_output_buffer_limit_pubsub,omitempty"`

	// (Boolean) Permits Pub/Sub shard operations when cluster is down. Can be either true or false.
	// Permits Pub/Sub shard operations when cluster is down. Can be either true or false.
	// +kubebuilder:validation:Optional
	ClusterAllowPubsubshardWhenDown *bool `json:"clusterAllowPubsubshardWhenDown,omitempty" tf:"cluster_allow_pubsubshard_when_down,omitempty"`

	// (Boolean) Allows read operations when cluster is down. Can be either true or false.
	// Allows read operations when cluster is down. Can be either true or false.
	// +kubebuilder:validation:Optional
	ClusterAllowReadsWhenDown *bool `json:"clusterAllowReadsWhenDown,omitempty" tf:"cluster_allow_reads_when_down,omitempty"`

	// (Boolean) Controls whether all hash slots must be covered by nodes. Can be either true or false.
	// Controls whether all hash slots must be covered by nodes. Can be either true or false.
	// +kubebuilder:validation:Optional
	ClusterRequireFullCoverage *bool `json:"clusterRequireFullCoverage,omitempty" tf:"cluster_require_full_coverage,omitempty"`

	// server process.
	// Number of database buckets on a single redis-server process.
	// +kubebuilder:validation:Optional
	Databases *float64 `json:"databases,omitempty" tf:"databases,omitempty"`

	// threads. Can be either true or false.
	// Allow redis to use io-threads. Can be either true or false.
	// +kubebuilder:validation:Optional
	IoThreadsAllowed *bool `json:"ioThreadsAllowed,omitempty" tf:"io_threads_allowed,omitempty"`

	// (Number) The time, in minutes, that must elapse in order for the key counter to be divided by two (or decremented if it has a value less <= 10).
	// The time, in minutes, that must elapse in order for the key counter to be divided by two (or decremented if it has a value less <= 10).
	// +kubebuilder:validation:Optional
	LfuDecayTime *float64 `json:"lfuDecayTime,omitempty" tf:"lfu_decay_time,omitempty"`

	// (Number) Determines how the frequency counter represents key hits.
	// Determines how the frequency counter represents key hits.
	// +kubebuilder:validation:Optional
	LfuLogFactor *float64 `json:"lfuLogFactor,omitempty" tf:"lfu_log_factor,omitempty"`

	// disabled mechanism.
	// Maximum time in milliseconds for Lua scripts, 0 - disabled mechanism.
	// +kubebuilder:validation:Optional
	LuaTimeLimit *float64 `json:"luaTimeLimit,omitempty" tf:"lua_time_limit,omitempty"`

	// (Number) Redis maxmemory percent
	// Redis maxmemory percent
	// +kubebuilder:validation:Optional
	MaxmemoryPercent *float64 `json:"maxmemoryPercent,omitempty" tf:"maxmemory_percent,omitempty"`

	// (String) Redis key eviction policy for a dataset that reaches maximum memory, available to the host.
	// Redis key eviction policy for a dataset that reaches maximum memory, available to the host.
	// +kubebuilder:validation:Optional
	MaxmemoryPolicy *string `json:"maxmemoryPolicy,omitempty" tf:"maxmemory_policy,omitempty"`

	// (String) String setting for pub\sub functionality.
	// String setting for pub\sub functionality.
	// +kubebuilder:validation:Optional
	NotifyKeyspaceEvents *string `json:"notifyKeyspaceEvents,omitempty" tf:"notify_keyspace_events,omitempty"`

	// (String, Sensitive) Authentication password.
	// Authentication password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Number) Replication backlog size as a percentage of flavor maxmemory.
	// Replication backlog size as a percentage of flavor maxmemory.
	// +kubebuilder:validation:Optional
	ReplBacklogSizePercent *float64 `json:"replBacklogSizePercent,omitempty" tf:"repl_backlog_size_percent,omitempty"`

	// (Number) Threshold for logging slow requests to server in microseconds (log only slower than it).
	// Threshold for logging slow requests to server in microseconds (log only slower than it).
	// +kubebuilder:validation:Optional
	SlowlogLogSlowerThan *float64 `json:"slowlogLogSlowerThan,omitempty" tf:"slowlog_log_slower_than,omitempty"`

	// (Number) Max slow requests number to log.
	// Max slow requests number to log.
	// +kubebuilder:validation:Optional
	SlowlogMaxLen *float64 `json:"slowlogMaxLen,omitempty" tf:"slowlog_max_len,omitempty"`

	// (Number) Time that Redis keeps the connection open while the client is idle.
	// Time that Redis keeps the connection open while the client is idle.
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (Boolean) Allows to turn before switchover in RDSync. Can be either true or false.
	// Allows to turn before switchover in RDSync. Can be either true or false.
	// +kubebuilder:validation:Optional
	TurnBeforeSwitchover *bool `json:"turnBeforeSwitchover,omitempty" tf:"turn_before_switchover,omitempty"`

	// (Boolean) Use JIT for lua scripts and functions. Can be either true or false.
	// Use JIT for lua scripts and functions. Can be either true or false.
	// +kubebuilder:validation:Optional
	UseLuajit *bool `json:"useLuajit,omitempty" tf:"use_luajit,omitempty"`

	// (String) Redis version.
	// Redis version.
	// +kubebuilder:validation:Optional
	Version *string `json:"version" tf:"version,omitempty"`

	// efficient listpack to CPU-efficient hash table and skiplist
	// Controls max number of entries in zset before conversion from memory-efficient listpack to CPU-efficient hash table and skiplist
	// +kubebuilder:validation:Optional
	ZsetMaxListpackEntries *float64 `json:"zsetMaxListpackEntries,omitempty" tf:"zset_max_listpack_entries,omitempty"`
}

type RedisClusterV2DiskSizeAutoscalingInitParameters struct {

	// (Number) Limit of disk size after autoscaling (GiB).
	// Limit of disk size after autoscaling (GiB).
	DiskSizeLimit *float64 `json:"diskSizeLimit,omitempty" tf:"disk_size_limit,omitempty"`

	// (Number) Immediate autoscaling disk usage (percent).
	// Immediate autoscaling disk usage (percent).
	EmergencyUsageThreshold *float64 `json:"emergencyUsageThreshold,omitempty" tf:"emergency_usage_threshold,omitempty"`

	// (Number) Maintenance window autoscaling disk usage (percent).
	// Maintenance window autoscaling disk usage (percent).
	PlannedUsageThreshold *float64 `json:"plannedUsageThreshold,omitempty" tf:"planned_usage_threshold,omitempty"`
}

type RedisClusterV2DiskSizeAutoscalingObservation struct {

	// (Number) Limit of disk size after autoscaling (GiB).
	// Limit of disk size after autoscaling (GiB).
	DiskSizeLimit *float64 `json:"diskSizeLimit,omitempty" tf:"disk_size_limit,omitempty"`

	// (Number) Immediate autoscaling disk usage (percent).
	// Immediate autoscaling disk usage (percent).
	EmergencyUsageThreshold *float64 `json:"emergencyUsageThreshold,omitempty" tf:"emergency_usage_threshold,omitempty"`

	// (Number) Maintenance window autoscaling disk usage (percent).
	// Maintenance window autoscaling disk usage (percent).
	PlannedUsageThreshold *float64 `json:"plannedUsageThreshold,omitempty" tf:"planned_usage_threshold,omitempty"`
}

type RedisClusterV2DiskSizeAutoscalingParameters struct {

	// (Number) Limit of disk size after autoscaling (GiB).
	// Limit of disk size after autoscaling (GiB).
	// +kubebuilder:validation:Optional
	DiskSizeLimit *float64 `json:"diskSizeLimit" tf:"disk_size_limit,omitempty"`

	// (Number) Immediate autoscaling disk usage (percent).
	// Immediate autoscaling disk usage (percent).
	// +kubebuilder:validation:Optional
	EmergencyUsageThreshold *float64 `json:"emergencyUsageThreshold,omitempty" tf:"emergency_usage_threshold,omitempty"`

	// (Number) Maintenance window autoscaling disk usage (percent).
	// Maintenance window autoscaling disk usage (percent).
	// +kubebuilder:validation:Optional
	PlannedUsageThreshold *float64 `json:"plannedUsageThreshold,omitempty" tf:"planned_usage_threshold,omitempty"`
}

type RedisClusterV2HostsInitParameters struct {

	// (Boolean) Assign a public IP address to the host. Can be either true or false.
	// Assign a public IP address to the host. Can be either true or false.
	AssignPublicIP *bool `json:"assignPublicIp,omitempty" tf:"assign_public_ip,omitempty"`

	// (Number) A replica with a low priority number is considered better for promotion.
	// A replica with a low priority number is considered better for promotion.
	ReplicaPriority *float64 `json:"replicaPriority,omitempty" tf:"replica_priority,omitempty"`

	// (String) Shard Name of the host in the cluster.
	// Shard Name of the host in the cluster.
	ShardName *string `json:"shardName,omitempty" tf:"shard_name,omitempty"`

	// (String) ID of the subnet where the host is located.
	// ID of the subnet where the host is located.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// (String) The availability zone where resource is located. If it is not provided, the default provider zone will be used.
	// The [availability zone](https://yandex.cloud/docs/overview/concepts/geo-scope) where resource is located. If it is not provided, the default provider zone will be used.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type RedisClusterV2HostsObservation struct {

	// (Boolean) Assign a public IP address to the host. Can be either true or false.
	// Assign a public IP address to the host. Can be either true or false.
	AssignPublicIP *bool `json:"assignPublicIp,omitempty" tf:"assign_public_ip,omitempty"`

	// (String) Fully Qualified Domain Name. In other words, hostname.
	// Fully Qualified Domain Name. In other words, hostname.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// (Number) A replica with a low priority number is considered better for promotion.
	// A replica with a low priority number is considered better for promotion.
	ReplicaPriority *float64 `json:"replicaPriority,omitempty" tf:"replica_priority,omitempty"`

	// (String) Shard Name of the host in the cluster.
	// Shard Name of the host in the cluster.
	ShardName *string `json:"shardName,omitempty" tf:"shard_name,omitempty"`

	// (String) ID of the subnet where the host is located.
	// ID of the subnet where the host is located.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// (String) The availability zone where resource is located. If it is not provided, the default provider zone will be used.
	// The [availability zone](https://yandex.cloud/docs/overview/concepts/geo-scope) where resource is located. If it is not provided, the default provider zone will be used.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type RedisClusterV2HostsParameters struct {

	// (Boolean) Assign a public IP address to the host. Can be either true or false.
	// Assign a public IP address to the host. Can be either true or false.
	// +kubebuilder:validation:Optional
	AssignPublicIP *bool `json:"assignPublicIp,omitempty" tf:"assign_public_ip,omitempty"`

	// (Number) A replica with a low priority number is considered better for promotion.
	// A replica with a low priority number is considered better for promotion.
	// +kubebuilder:validation:Optional
	ReplicaPriority *float64 `json:"replicaPriority,omitempty" tf:"replica_priority,omitempty"`

	// (String) Shard Name of the host in the cluster.
	// Shard Name of the host in the cluster.
	// +kubebuilder:validation:Optional
	ShardName *string `json:"shardName,omitempty" tf:"shard_name,omitempty"`

	// (String) ID of the subnet where the host is located.
	// ID of the subnet where the host is located.
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// (String) The availability zone where resource is located. If it is not provided, the default provider zone will be used.
	// The [availability zone](https://yandex.cloud/docs/overview/concepts/geo-scope) where resource is located. If it is not provided, the default provider zone will be used.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone" tf:"zone,omitempty"`
}

type RedisClusterV2InitParameters struct {

	// (Attributes) Access policy to the Redis cluster. (see below for nested schema)
	Access *RedisClusterV2AccessInitParameters `json:"access,omitempty" tf:"access,omitempty"`

	// (Boolean) Announce fqdn instead of ip address. Can be either true or false.
	// Announce fqdn instead of ip address. Can be either true or false.
	AnnounceHostnames *bool `json:"announceHostnames,omitempty" tf:"announce_hostnames,omitempty"`

	// (Boolean) Allows to use ACL users to auth in sentinel
	// Allows to use ACL users to auth in sentinel
	AuthSentinel *bool `json:"authSentinel,omitempty" tf:"auth_sentinel,omitempty"`

	// (Attributes) Configuration of the Redis cluster. (see below for nested schema)
	Config *RedisClusterV2ConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (Boolean) The true value means that resource is protected from accidental deletion.
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// (String) The resource description.
	// The resource description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) ID of the symmetric encryption key used to encrypt the disk of the cluster.
	// ID of the symmetric encryption key used to encrypt the disk of the cluster.
	DiskEncryptionKeyID *string `json:"diskEncryptionKeyId,omitempty" tf:"disk_encryption_key_id,omitempty"`

	// (Attributes) Disk size autoscaling settings. (see below for nested schema)
	DiskSizeAutoscaling *RedisClusterV2DiskSizeAutoscalingInitParameters `json:"diskSizeAutoscaling,omitempty" tf:"disk_size_autoscaling,omitempty"`

	// (String) Deployment environment of the Redis cluster.
	// Deployment environment of the Redis cluster.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// id is used.
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	// +crossplane:generate:reference:type=github.com/tagesjump/provider-upjet-yc/apis/cluster/resourcemanager/v1alpha1.Folder
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// Reference to a Folder in resourcemanager to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDRef *v1.Reference `json:"folderIdRef,omitempty" tf:"-"`

	// Selector for a Folder in resourcemanager to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDSelector *v1.Selector `json:"folderIdSelector,omitempty" tf:"-"`

	// (Attributes Map) A hosts of the Redis cluster as label:host_info pairs. (see below for nested schema)
	Hosts map[string]RedisClusterV2HostsInitParameters `json:"hosts,omitempty" tf:"hosts,omitempty"`

	// (Map of String) A set of key/value label pairs which assigned to resource.
	// A set of key/value label pairs which assigned to resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) Maintenance window settings of the Redis cluster. (see below for nested schema)
	MaintenanceWindow *RedisClusterV2MaintenanceWindowInitParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (Attributes) Valkey modules. (see below for nested schema)
	Modules *ModulesInitParameters `json:"modules,omitempty" tf:"modules,omitempty"`

	// (String) The resource name.
	// The resource name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The VPC Network ID of subnets which resource attached to.
	// The `VPC Network ID` of subnets which resource attached to.
	// +crossplane:generate:reference:type=github.com/tagesjump/provider-upjet-yc/apis/cluster/vpc/v1alpha1.Network
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) Persistence mode.
	// Persistence mode.
	PersistenceMode *string `json:"persistenceMode,omitempty" tf:"persistence_mode,omitempty"`

	// (Attributes) Resources allocated to hosts of the Redis cluster. (see below for nested schema)
	Resources *RedisClusterV2ResourcesInitParameters `json:"resources,omitempty" tf:"resources,omitempty"`

	// (Set of String) The list of security groups applied to resource or their components.
	// The list of security groups applied to resource or their components.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Boolean) Redis sharded mode. Can be either true or false.
	// Redis sharded mode. Can be either true or false.
	Sharded *bool `json:"sharded,omitempty" tf:"sharded,omitempty"`

	// (Boolean) TLS port and functionality. Can be either true or false.
	// TLS port and functionality. Can be either true or false.
	TLSEnabled *bool `json:"tlsEnabled,omitempty" tf:"tls_enabled,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *RedisClusterV2TimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type RedisClusterV2MaintenanceWindowInitParameters struct {

	// (String) Day of week for maintenance window if window type is weekly.
	// Day of week for maintenance window if window type is weekly.
	Day *string `json:"day,omitempty" tf:"day,omitempty"`

	// 24) for maintenance window if window type is weekly.
	// Hour of day in UTC time zone (1-24) for maintenance window if window type is weekly.
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`

	// (String) Type of maintenance window.
	// Type of maintenance window.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RedisClusterV2MaintenanceWindowObservation struct {

	// (String) Day of week for maintenance window if window type is weekly.
	// Day of week for maintenance window if window type is weekly.
	Day *string `json:"day,omitempty" tf:"day,omitempty"`

	// 24) for maintenance window if window type is weekly.
	// Hour of day in UTC time zone (1-24) for maintenance window if window type is weekly.
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`

	// (String) Type of maintenance window.
	// Type of maintenance window.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RedisClusterV2MaintenanceWindowParameters struct {

	// (String) Day of week for maintenance window if window type is weekly.
	// Day of week for maintenance window if window type is weekly.
	// +kubebuilder:validation:Optional
	Day *string `json:"day,omitempty" tf:"day,omitempty"`

	// 24) for maintenance window if window type is weekly.
	// Hour of day in UTC time zone (1-24) for maintenance window if window type is weekly.
	// +kubebuilder:validation:Optional
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`

	// (String) Type of maintenance window.
	// Type of maintenance window.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type RedisClusterV2Observation struct {

	// (Attributes) Access policy to the Redis cluster. (see below for nested schema)
	Access *RedisClusterV2AccessObservation `json:"access,omitempty" tf:"access,omitempty"`

	// (Boolean) Announce fqdn instead of ip address. Can be either true or false.
	// Announce fqdn instead of ip address. Can be either true or false.
	AnnounceHostnames *bool `json:"announceHostnames,omitempty" tf:"announce_hostnames,omitempty"`

	// (Boolean) Allows to use ACL users to auth in sentinel
	// Allows to use ACL users to auth in sentinel
	AuthSentinel *bool `json:"authSentinel,omitempty" tf:"auth_sentinel,omitempty"`

	// (String) ID of the Redis cluster. This ID is assigned by MDB at creation time.
	// ID of the Redis cluster. This ID is assigned by MDB at creation time.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Attributes) Configuration of the Redis cluster. (see below for nested schema)
	Config *RedisClusterV2ConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The creation timestamp of the resource.
	// The creation timestamp of the resource.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) The true value means that resource is protected from accidental deletion.
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// (String) The resource description.
	// The resource description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) ID of the symmetric encryption key used to encrypt the disk of the cluster.
	// ID of the symmetric encryption key used to encrypt the disk of the cluster.
	DiskEncryptionKeyID *string `json:"diskEncryptionKeyId,omitempty" tf:"disk_encryption_key_id,omitempty"`

	// (Attributes) Disk size autoscaling settings. (see below for nested schema)
	DiskSizeAutoscaling *RedisClusterV2DiskSizeAutoscalingObservation `json:"diskSizeAutoscaling,omitempty" tf:"disk_size_autoscaling,omitempty"`

	// (String) Deployment environment of the Redis cluster.
	// Deployment environment of the Redis cluster.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// id is used.
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// (Attributes Map) A hosts of the Redis cluster as label:host_info pairs. (see below for nested schema)
	Hosts map[string]RedisClusterV2HostsObservation `json:"hosts,omitempty" tf:"hosts,omitempty"`

	// (String) The resource identifier.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) A set of key/value label pairs which assigned to resource.
	// A set of key/value label pairs which assigned to resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) Maintenance window settings of the Redis cluster. (see below for nested schema)
	MaintenanceWindow *RedisClusterV2MaintenanceWindowObservation `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (Attributes) Valkey modules. (see below for nested schema)
	Modules *ModulesObservation `json:"modules,omitempty" tf:"modules,omitempty"`

	// (String) The resource name.
	// The resource name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The VPC Network ID of subnets which resource attached to.
	// The `VPC Network ID` of subnets which resource attached to.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (String) Persistence mode.
	// Persistence mode.
	PersistenceMode *string `json:"persistenceMode,omitempty" tf:"persistence_mode,omitempty"`

	// (Attributes) Resources allocated to hosts of the Redis cluster. (see below for nested schema)
	Resources *RedisClusterV2ResourcesObservation `json:"resources,omitempty" tf:"resources,omitempty"`

	// (Set of String) The list of security groups applied to resource or their components.
	// The list of security groups applied to resource or their components.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Boolean) Redis sharded mode. Can be either true or false.
	// Redis sharded mode. Can be either true or false.
	Sharded *bool `json:"sharded,omitempty" tf:"sharded,omitempty"`

	// (Boolean) TLS port and functionality. Can be either true or false.
	// TLS port and functionality. Can be either true or false.
	TLSEnabled *bool `json:"tlsEnabled,omitempty" tf:"tls_enabled,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *RedisClusterV2TimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type RedisClusterV2Parameters struct {

	// (Attributes) Access policy to the Redis cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Access *RedisClusterV2AccessParameters `json:"access,omitempty" tf:"access,omitempty"`

	// (Boolean) Announce fqdn instead of ip address. Can be either true or false.
	// Announce fqdn instead of ip address. Can be either true or false.
	// +kubebuilder:validation:Optional
	AnnounceHostnames *bool `json:"announceHostnames,omitempty" tf:"announce_hostnames,omitempty"`

	// (Boolean) Allows to use ACL users to auth in sentinel
	// Allows to use ACL users to auth in sentinel
	// +kubebuilder:validation:Optional
	AuthSentinel *bool `json:"authSentinel,omitempty" tf:"auth_sentinel,omitempty"`

	// (Attributes) Configuration of the Redis cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Config *RedisClusterV2ConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (Boolean) The true value means that resource is protected from accidental deletion.
	// The `true` value means that resource is protected from accidental deletion.
	// +kubebuilder:validation:Optional
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// (String) The resource description.
	// The resource description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) ID of the symmetric encryption key used to encrypt the disk of the cluster.
	// ID of the symmetric encryption key used to encrypt the disk of the cluster.
	// +kubebuilder:validation:Optional
	DiskEncryptionKeyID *string `json:"diskEncryptionKeyId,omitempty" tf:"disk_encryption_key_id,omitempty"`

	// (Attributes) Disk size autoscaling settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	DiskSizeAutoscaling *RedisClusterV2DiskSizeAutoscalingParameters `json:"diskSizeAutoscaling,omitempty" tf:"disk_size_autoscaling,omitempty"`

	// (String) Deployment environment of the Redis cluster.
	// Deployment environment of the Redis cluster.
	// +kubebuilder:validation:Optional
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// id is used.
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	// +crossplane:generate:reference:type=github.com/tagesjump/provider-upjet-yc/apis/cluster/resourcemanager/v1alpha1.Folder
	// +kubebuilder:validation:Optional
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// Reference to a Folder in resourcemanager to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDRef *v1.Reference `json:"folderIdRef,omitempty" tf:"-"`

	// Selector for a Folder in resourcemanager to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDSelector *v1.Selector `json:"folderIdSelector,omitempty" tf:"-"`

	// (Attributes Map) A hosts of the Redis cluster as label:host_info pairs. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Hosts map[string]RedisClusterV2HostsParameters `json:"hosts,omitempty" tf:"hosts,omitempty"`

	// (Map of String) A set of key/value label pairs which assigned to resource.
	// A set of key/value label pairs which assigned to resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) Maintenance window settings of the Redis cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	MaintenanceWindow *RedisClusterV2MaintenanceWindowParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (Attributes) Valkey modules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Modules *ModulesParameters `json:"modules,omitempty" tf:"modules,omitempty"`

	// (String) The resource name.
	// The resource name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The VPC Network ID of subnets which resource attached to.
	// The `VPC Network ID` of subnets which resource attached to.
	// +crossplane:generate:reference:type=github.com/tagesjump/provider-upjet-yc/apis/cluster/vpc/v1alpha1.Network
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) Persistence mode.
	// Persistence mode.
	// +kubebuilder:validation:Optional
	PersistenceMode *string `json:"persistenceMode,omitempty" tf:"persistence_mode,omitempty"`

	// (Attributes) Resources allocated to hosts of the Redis cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Resources *RedisClusterV2ResourcesParameters `json:"resources,omitempty" tf:"resources,omitempty"`

	// (Set of String) The list of security groups applied to resource or their components.
	// The list of security groups applied to resource or their components.
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Boolean) Redis sharded mode. Can be either true or false.
	// Redis sharded mode. Can be either true or false.
	// +kubebuilder:validation:Optional
	Sharded *bool `json:"sharded,omitempty" tf:"sharded,omitempty"`

	// (Boolean) TLS port and functionality. Can be either true or false.
	// TLS port and functionality. Can be either true or false.
	// +kubebuilder:validation:Optional
	TLSEnabled *bool `json:"tlsEnabled,omitempty" tf:"tls_enabled,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Timeouts *RedisClusterV2TimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type RedisClusterV2ResourcesInitParameters struct {

	// (Number) Volume of the storage available to a host, in gigabytes.
	// Volume of the storage available to a host, in gigabytes.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (String) ID of the disk type that determines the disk performance characteristics.
	// ID of the disk type that determines the disk performance characteristics.
	DiskTypeID *string `json:"diskTypeId,omitempty" tf:"disk_type_id,omitempty"`

	// (String) ID of the resource preset that determines the number of CPU cores and memory size for the host.
	// ID of the resource preset that determines the number of CPU cores and memory size for the host.
	ResourcePresetID *string `json:"resourcePresetId,omitempty" tf:"resource_preset_id,omitempty"`
}

type RedisClusterV2ResourcesObservation struct {

	// (Number) Volume of the storage available to a host, in gigabytes.
	// Volume of the storage available to a host, in gigabytes.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (String) ID of the disk type that determines the disk performance characteristics.
	// ID of the disk type that determines the disk performance characteristics.
	DiskTypeID *string `json:"diskTypeId,omitempty" tf:"disk_type_id,omitempty"`

	// (String) ID of the resource preset that determines the number of CPU cores and memory size for the host.
	// ID of the resource preset that determines the number of CPU cores and memory size for the host.
	ResourcePresetID *string `json:"resourcePresetId,omitempty" tf:"resource_preset_id,omitempty"`
}

type RedisClusterV2ResourcesParameters struct {

	// (Number) Volume of the storage available to a host, in gigabytes.
	// Volume of the storage available to a host, in gigabytes.
	// +kubebuilder:validation:Optional
	DiskSize *float64 `json:"diskSize" tf:"disk_size,omitempty"`

	// (String) ID of the disk type that determines the disk performance characteristics.
	// ID of the disk type that determines the disk performance characteristics.
	// +kubebuilder:validation:Optional
	DiskTypeID *string `json:"diskTypeId,omitempty" tf:"disk_type_id,omitempty"`

	// (String) ID of the resource preset that determines the number of CPU cores and memory size for the host.
	// ID of the resource preset that determines the number of CPU cores and memory size for the host.
	// +kubebuilder:validation:Optional
	ResourcePresetID *string `json:"resourcePresetId" tf:"resource_preset_id,omitempty"`
}

type RedisClusterV2TimeoutsInitParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type RedisClusterV2TimeoutsObservation struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type RedisClusterV2TimeoutsParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ValkeyBloomInitParameters struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey bloom module.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ValkeyBloomObservation struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey bloom module.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ValkeyBloomParameters struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey bloom module.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ValkeyJSONInitParameters struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey json module.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ValkeyJSONObservation struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey json module.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ValkeyJSONParameters struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey json module.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ValkeySearchInitParameters struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey search module.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Number of reader threads.
	// Number of reader threads.
	ReaderThreads *float64 `json:"readerThreads,omitempty" tf:"reader_threads,omitempty"`

	// (Number) Number of writer threads.
	// Number of writer threads.
	WriterThreads *float64 `json:"writerThreads,omitempty" tf:"writer_threads,omitempty"`
}

type ValkeySearchObservation struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey search module.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Number of reader threads.
	// Number of reader threads.
	ReaderThreads *float64 `json:"readerThreads,omitempty" tf:"reader_threads,omitempty"`

	// (Number) Number of writer threads.
	// Number of writer threads.
	WriterThreads *float64 `json:"writerThreads,omitempty" tf:"writer_threads,omitempty"`
}

type ValkeySearchParameters struct {

	// (Boolean) Enable Valkey bloom module.
	// Enable Valkey search module.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Number of reader threads.
	// Number of reader threads.
	// +kubebuilder:validation:Optional
	ReaderThreads *float64 `json:"readerThreads,omitempty" tf:"reader_threads,omitempty"`

	// (Number) Number of writer threads.
	// Number of writer threads.
	// +kubebuilder:validation:Optional
	WriterThreads *float64 `json:"writerThreads,omitempty" tf:"writer_threads,omitempty"`
}

// RedisClusterV2Spec defines the desired state of RedisClusterV2
type RedisClusterV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RedisClusterV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RedisClusterV2InitParameters `json:"initProvider,omitempty"`
}

// RedisClusterV2Status defines the observed state of RedisClusterV2.
type RedisClusterV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RedisClusterV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RedisClusterV2 is the Schema for the RedisClusterV2s API. Manages a Redis cluster within Yandex Cloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,yandex-cloud}
type RedisClusterV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.config) || (has(self.initProvider) && has(self.initProvider.config))",message="spec.forProvider.config is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hosts) || (has(self.initProvider) && has(self.initProvider.hosts))",message="spec.forProvider.hosts is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resources) || (has(self.initProvider) && has(self.initProvider.resources))",message="spec.forProvider.resources is a required parameter"
	Spec   RedisClusterV2Spec   `json:"spec"`
	Status RedisClusterV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedisClusterV2List contains a list of RedisClusterV2s
type RedisClusterV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedisClusterV2 `json:"items"`
}

// Repository type metadata.
var (
	RedisClusterV2_Kind             = "RedisClusterV2"
	RedisClusterV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RedisClusterV2_Kind}.String()
	RedisClusterV2_KindAPIVersion   = RedisClusterV2_Kind + "." + CRDGroupVersion.String()
	RedisClusterV2_GroupVersionKind = CRDGroupVersion.WithKind(RedisClusterV2_Kind)
)

func init() {
	SchemeBuilder.Register(&RedisClusterV2{}, &RedisClusterV2List{})
}
