apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: MySQLUser
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqluser
  labels:
    testing.upbound.io/example-name: john
  name: john
spec:
  forProvider:
    authenticationPlugin: SHA256_PASSWORD
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    connectionLimits:
    - maxConnectionsPerHour: 30
      maxQuestionsPerHour: 10
      maxUpdatesPerHour: 20
      maxUserConnections: 40
    globalPermissions:
    - PROCESS
    name: john
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    permission:
    - databaseNameSelector:
        matchLabels:
          testing.upbound.io/example-name: testdb
      roles:
      - ALL
    - databaseNameSelector:
        matchLabels:
          testing.upbound.io/example-name: new_testdb
      roles:
      - ALL
      - INSERT

---

apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: MySQLCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqluser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    config:
    - resources:
      - disk_size: 16
        disk_type_id: network-ssd
        resource_preset_id: s2.micro
      version: 14
    environment: PRESTABLE
    host:
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
      zone: ru-central1-a
    name: test
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqluser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqluser
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.5.0.0/24
    zone: ru-central1-a
