apiVersion: mdb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: PostgresqlCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    config:
    - postgresqlConfig:
        autovacuum_vacuum_scale_factor: 0.34
        default_transaction_isolation: TRANSACTION_ISOLATION_READ_COMMITTED
        enable_parallel_hash: true
        max_connections: 395
        shared_preload_libraries: SHARED_PRELOAD_LIBRARIES_AUTO_EXPLAIN,SHARED_PRELOAD_LIBRARIES_PG_HINT_PLAN
      resources:
      - diskSize: 16
        diskTypeId: network-ssd
        resourcePresetId: s2.micro
      version: 15
    environment: PRESTABLE
    host:
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
      zone: ru-central1-a
    maintenanceWindow:
    - day: SAT
      hour: 12
      type: WEEKLY
    name: test
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    v4CidrBlocks:
    - 10.5.0.0/24
    zone: ru-central1-a
