apiVersion: yandex.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: yandex/v1alpha1/function
  labels:
    testing.upbound.io/example-name: test-function
  name: test-function
  namespace: upbound-system
spec:
  forProvider:
    asyncInvocation:
    - retriesCount: "3"
      serviceAccountId: ajeih**********838kk
      ymqFailureTarget:
      - arn: yrn:yc:ymq:ru-central1:b1glr**********9hsfp:fail
        serviceAccountId: ajeqr**********qb76m
      ymqSuccessTarget:
      - arn: yrn:yc:ymq:ru-central1:b1glr**********9hsfp:success
        serviceAccountId: ajeqr**********qb76m
    content:
    - zipFilename: function.zip
    description: any description
    entrypoint: main
    executionTimeout: "10"
    logOptions:
    - logGroupId: e2392**********eq9fr
      minLevel: ERROR
    memory: "128"
    mounts:
    - ephemeralDisk:
      - sizeGb: 32
      name: mnt
    name: some_name
    runtime: python37
    secrets:
    - environmentVariable: ENV_VARIABLE
      idSelector:
        matchLabels:
          testing.upbound.io/example-name: secret
      key: secret-key
      versionIdSelector:
        matchLabels:
          testing.upbound.io/example-name: secret_version
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
    - my_tag
    userHash: any_user_defined_string
