apiVersion: iam.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: ServiceAccountStaticAccessKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccountstaticaccesskey
  labels:
    testing.upbound.io/example-name: sa-static-key
  name: sa-static-key
  namespace: upbound-system
spec:
  forProvider:
    description: static access key for object storage
    pgpKey: keybase:keybaseusername
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
