apiVersion: compute.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: DiskPlacementGroupIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/diskplacementgroupiambinding
  labels:
    testing.upbound.io/example-name: editor
  name: editor
  namespace: upbound-system
spec:
  forProvider:
    diskPlacementGroupId: ${data.yandex_compute_disk_placement_group.group1.id}
    members:
    - userAccount:some_user_id
    role: editor

---

apiVersion: compute.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: DiskPlacementGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/diskplacementgroupiambinding
  labels:
    testing.upbound.io/example-name: group1
  name: group1
  namespace: upbound-system
spec:
  forProvider:
    description: my description
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: test-pg
