apiVersion: compute.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/image
  labels:
    testing.upbound.io/example-name: foo-image
  name: foo-image
  namespace: upbound-system
spec:
  forProvider:
    name: my-custom-image
    sourceUrl: https://storage.yandexcloud.net/lucky-images/kube-it.img

---

apiVersion: compute.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/image
  labels:
    testing.upbound.io/example-name: vm
  name: vm
  namespace: upbound-system
spec:
  forProvider:
    bootDisk:
    - initializeParams:
      - imageIdSelector:
          matchLabels:
            testing.upbound.io/example-name: foo-image
    name: vm-from-custom-image
