apiVersion: compute.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: InstanceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instancegroup
  labels:
    testing.upbound.io/example-name: group1
  name: group1
  namespace: upbound-system
spec:
  forProvider:
    allocationPolicy:
    - zones:
      - ru-central1-a
    deletionProtection: true
    deployPolicy:
    - maxCreating: 2
      maxDeleting: 2
      maxExpansion: 2
      maxUnavailable: 2
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager_folder
    instanceTemplate:
    - bootDisk:
      - initializeParams:
        - imageIdSelector:
            matchLabels:
              testing.upbound.io/example-name: yandex_compute_image
          size: 4
        mode: READ_WRITE
      labels:
        label1: label1-value
        label2: label2-value
      metadata:
        foo: bar
        ssh-keys: ubuntu:${file("~/.ssh/id_rsa.pub")}
      networkInterface:
      - networkIdSelector:
          matchLabels:
            testing.upbound.io/example-name: my-inst-group-network
        subnetIdsRefs:
        - name: my-inst-group-subnet
      networkSettings:
      - type: STANDARD
      platformId: standard-v1
      resources:
      - cores: 2
        memory: 2
    name: test-ig
    scalePolicy:
    - fixedScale:
      - size: 3
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_account
    variables:
      test_key1: test_value1
      test_key2: test_value2
