apiVersion: compute.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: InstanceIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instanceiambinding
  labels:
    testing.upbound.io/example-name: editor
  name: editor
  namespace: upbound-system
spec:
  forProvider:
    image_id: ${data.yandex_compute_instance.vm1.id}
    members:
    - userAccount:some_user_id
    role: editor

---

apiVersion: compute.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instanceiambinding
  labels:
    testing.upbound.io/example-name: vm1
  name: vm1
  namespace: upbound-system
spec:
  forProvider:
    bootDisk:
    - diskIdSelector:
        matchLabels:
          testing.upbound.io/example-name: boot-disk
    metadata:
      foo: bar
      ssh-keys: ubuntu:${file("~/.ssh/id_ed25519.pub")}
    name: test
    networkInterface:
    - index: 1
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
    platformId: standard-v3
    resources:
    - cores: 2
      memory: 4
    zone: ru-central1-a
