apiVersion: resourcemanager.crossplane.io/v1alpha1
kind: FolderIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: resourcemanager/v1alpha1/folderiammember
  labels:
    testing.upbound.io/example-name: admin
  name: admin
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager
    member: userAccount:user_id
    role: editor
