// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Registry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegistryIAMBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegistryIPPermission) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryIAMBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryLifecyclePolicy) Hub() {}
