apiVersion: lockbox.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: lockbox/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: my_secret
  name: my-secret
spec:
  forProvider:
    name: test secret
