apiVersion: alb.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: my_alb
  name: my-alb
  namespace: upbound-system
spec:
  forProvider:
    allocationPolicy:
    - location:
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test-subnet
        zoneId: ru-central1-a
    listener:
    - endpoint:
      - address:
        - externalIpv4Address:
          - {}
        ports:
        - 8080
      http:
      - handler:
        - httpRouterIdSelector:
            matchLabels:
              testing.upbound.io/example-name: test-router
      name: my-listener
    logOptions:
    - discardRule:
      - discardPercent: 75
        httpCodeIntervals:
        - 2XX
    name: my-load-balancer
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-network
