apiVersion: cloud.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: DesktopsDesktopGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/desktopsdesktopgroup
  labels:
    testing.upbound.io/example-name: desktop_group
  name: desktop-group
spec:
  forProvider:
    description: Sample description
    desktopTemplate:
      bootDisk:
        initializeParams:
          size: 24
          type: SSD
      dataDisk:
        initializeParams:
          size: 16
          type: HDD
      networkInterface:
        networkId: ${yandex_vpc_network.network.id}
        subnetIds:
        - ${yandex_vpc_subnet.subnet.id}
      resources:
        coreFraction: 100
        cores: 4
        memory: 8
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    groupConfig:
      desktopType: PERSISTENT
      maxDesktopsAmount: 5
      members:
      - id: <your id>
        type: userAccount
      minReadyDesktops: 1
    imageId: ${data.yandex_cloud_desktops_image.image.id}
    labels:
      label1: label1-value
      label2: label2-value
    name: desktop-group-name

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/desktopsdesktopgroup
  labels:
    testing.upbound.io/example-name: network
  name: network
spec:
  forProvider: {}

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/desktopsdesktopgroup
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network
    v4CidrBlocks:
    - 10.1.0.0/24
    zone: ru-central1-a
