apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: DefaultSecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/defaultsecuritygroup
  labels:
    testing.upbound.io/example-name: default-sg
  name: default-sg
spec:
  forProvider:
    description: description for default security group
    egress:
    - description: rule2 description
      fromPort: 8090
      protocol: ANY
      toPort: 8099
      v4CidrBlocks:
      - 10.0.1.0/24
      - 10.0.2.0/24
    - description: rule3 description
      fromPort: 8090
      protocol: UDP
      toPort: 8099
      v4CidrBlocks:
      - 10.0.1.0/24
    ingress:
    - description: rule1 description
      port: 8080
      protocol: TCP
      v4CidrBlocks:
      - 10.0.1.0/24
      - 10.0.2.0/24
    labels:
      my-label: my-label-value
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: lab-net

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/defaultsecuritygroup
  labels:
    testing.upbound.io/example-name: lab-net
  name: lab-net
spec:
  forProvider:
    name: lab-network
