apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/securitygrouprule
  labels:
    testing.upbound.io/example-name: rule1
  name: rule1
spec:
  forProvider:
    description: rule1 description
    direction: ingress
    port: 8080
    protocol: TCP
    securityGroupBindingSelector:
      matchLabels:
        testing.upbound.io/example-name: group1
    v4CidrBlocks:
    - 10.0.1.0/24
    - 10.0.2.0/24

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/securitygrouprule
  labels:
    testing.upbound.io/example-name: lab-net
  name: lab-net
spec:
  forProvider:
    name: lab-network

---

apiVersion: vpc.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/securitygrouprule
  labels:
    testing.upbound.io/example-name: group1
  name: group1
spec:
  forProvider:
    description: description for my security group
    labels:
      my-label: my-label-value
    name: My security group
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: lab-net
